### ISSUE TITLE
質問：02:プロジェクト作成動画について

### ISSUE THREAD

**Issue by TM-k-nakagawa** [HyunwookPark/question-box#10]
質問が2つあります。

動画内のMotosController.java内の記述にて
 @RequestMapping("/hello")
    public String hello(@RequestParam String name, Model model) {
        model.addAttribute("name", name);
        return "test";    
    }
とありますが、String nameはブラウザの入力する?name=ぱくぱくの部分であることは理解できました。

・Model modelと書いてあるのは、Test.htmlに渡すModelに情報を入れていることまでは理解できたのですが、Model modelと
２つ記述する理由がわからないです。
・model.addAttribute("name", name);の記述では、("name", name)をmodelに追加にしていることまでは理解しているのですが、Modelに"name"と名前を付けている認識であっているのでしょうか？

**Comment by HyunwookPark** [comment]
@TM-k-nakagawa 
質問ありがとうございます！

> Model modelと書いてあるのは、Test.htmlに渡すModelに情報を入れていることまでは理解できたのですが、Model modelと２つ記述する理由がわからないです。

これはクラスとインスタンスの関係ですね。
`Model`はインターフェース名で`model`はインスタンス名です。
`Model`はSpringフレームワークで提供されるインターフェースなので変更の余地はありませんが、
`model`はインスタンス変数なので好きな名称にできます。

```java
public String hello(@RequestParam String name, Model iremono) {
    iremono.addAttribute("name", name);
    return "test";
}
```

こんな風にしてもOKです。

**Comment by HyunwookPark** [comment]
@TM-k-nakagawa 

> model.addAttribute("name", name);の記述では、("name", name)をmodelに追加にしていることまでは理解しているのですが、Modelに"name"と名前を付けている認識であっているのでしょうか？

`Model`はJavaのMapのようにキーと値をセットで入れられる入れ物です。
`"name"`の部分はそのキーの部分に相当します。

これはThymeleafで値を取り出すときに使います。

キー名を変えて表現するとこんな感じです。

**MotosController.java**

```java
model.addAttribute("key", name);
```

**tes.html**

```html
<span th:text="${key}"></span>
```

**Comment by HyunwookPark** [comment]
@TM-k-nakagawa 

ちなみに`@RequestParam String name`の部分は
リクエスト時のクエリパラメータの名前（つまり`?name=ぱくぱく`のname）と合わせる必要があります。

**Comment by TM-k-nakagawa** [comment]
@HyunwookPark 
早速のお返事ありがとうございます。
今後も質問することがあるかと思いますのでどうかよろしくお願いいたします。
