### ISSUE TITLE
application.ymlとapplication.propertiesについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#11]
9月度受講時から疑問に思っていたことです。
ecripseでは標準が「application.properties」となっているので、基本application.propertiesを使用していました。
application.ymlとは記述内容が全然違うと感じていて、インデントでエラーになることもあり敬遠しています。
要は難しいと感じています💦

ecripseにapplication.propertiesには「.propertiesを.ymlに変換」という項目があり、自動的に変換してくれます。
逆の機能は見当たらないのですが、.ymlを.propertiesに変換する方法はありますか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> 要は難しいと感じています💦

そこは好みでいいと思います。

私はインデントがあって文字数も少なく見やすいと感じる人です。
また、ymlは同じ関連の設定が必然的にまとまるのでいいと思っています。

ただ、propertiesだと1行ずつのコメントアウトしやすい面でいい部分もあります。
yokoさんのようにそもそもpropertiesの方が見やすい人もいますしね。

> ecripseにapplication.propertiesには「.propertiesを.ymlに変換」という項目があり、自動的に変換してくれます。

propeties→ymlの自動変換は知りませんでした。
そんな機能があったんですね。勉強になります。

> 逆の機能は見当たらないのですが、.ymlを.propertiesに変換する方法はありますか。

ざっとググってみた感じだと見当たらないですね。
また時間のあるときに探してみます。

**Comment by yoko-Developer** [comment]
どちらもできる方がよいと思っています。
もし見つけたら、教えてください！
よろしくお願いします。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
書いてある内容は変わらないのでどちらか一方で見れるようになれば仕事上は問題ないと思いますよ。

**Comment by yoko-Developer** [comment]
今回はymlでやってみます！
ありがとうございました。
