### ISSUE TITLE
MySQLの起動について

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#12]
`docker ps -a`
を実行した時に表示される内容を見ても、MySQLの状態が理解できません。
こんな質問で申し訳ないのですが、判断の仕方を教えていただけないでしょうか。
![D490DFF0-A6A5-426A-B056-C2D8BE4E926E_1_201_a](https://user-images.githubusercontent.com/91002836/198864159-6cc7ef0b-3c0d-461e-9768-dbbb6dcc704a.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
`docker ps -a`ではdockerコンテナの状態だけが確認できます。
添付キャプチャーの状態であればMySQLのコンテナが起動している状態です。
`STATUS`が`UP`となっているので起動していることがわかります。

![image](https://user-images.githubusercontent.com/22320079/198864219-75651b37-56e4-4f51-aeec-96ea465d6c9a.png)

ただ、コンテナの中のMySQLがどんな状態なのかはわからないので
コンテナの中に入ってコマンドを使ってMySQLの状態を確認するかSQLツールでアクセスして状態を確認する必要があります。

ちなみにコンテナに入る場合はこんな感じで入れます。

> docker exec -it motocatalog-db-1 /bin/bash

**Comment by yoko-Developer** [comment]
コンテナ（docker）の起動状態を確認するコマンドなのですね。
6日間起動したまま・・。
コンテナに入って、dockerの操作ができるということでしょうか。
色々調べてみたいと思います。
ありがとうございます。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> コンテナに入って、dockerの操作ができるということでしょうか。

そうですそうです。
コンテナ中はLinuxの世界です。
ぜひ楽しんでください！(*ﾟ∀ﾟ*)

**Comment by yoko-Developer** [comment]
色々勉強したいと思います。
いつも些細な初心者の疑問に答えていただいて、ありがとうございます！
