### ISSUE TITLE
MyBatisのエラー？

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#13]
テスト[009]を実装したところでエラーが表示されてしまいました。
[008]までテスト実行できていたのに、全てエラーになってしまうのはおかしいと思っています。
dockerは起動しています。
エラー内容：org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): jp.co.planaria.sample.motocatalog.
数時間調べた結果、MyBatisのエラーだとおもいましたが、build.gradleに何か記載すべきでしょうか。一応キャプチャを貼ります。

何度かvscodeを再起動したのですが、Gitとbuildエラーも表示されます。
関係ないかもしれませんが、これは放置していて大丈夫なのでしょうか。

またまた質問、よろしくお願いします。
![42FBB4B4-34C1-4618-A1AA-64BF31DFA209](https://user-images.githubusercontent.com/91002836/200172894-1959cdf8-7678-41e5-b755-08466c321f20.jpeg)
![7B4C80F7-EFD5-4DB0-BC04-D5DF5156BCD1](https://user-images.githubusercontent.com/91002836/200172907-1d0b2adf-9472-4f5b-adcd-a5cb8017b9f1.jpeg)
![2A8D6C7E-8865-40EB-A54B-E754BC2B0B3E](https://user-images.githubusercontent.com/91002836/200172911-579ad134-8f2c-4cc6-bb32-59d5de0e61b8.jpeg)
![BA8192AF-8556-4466-9CE1-323007E0BB61_1_201_a](https://user-images.githubusercontent.com/91002836/200172917-ecc8a6f2-bf79-4326-a80f-ca52234a8188.jpeg)
![567A687C-AA9E-40D1-A4F2-D2D76003F689_1_201_a](https://user-images.githubusercontent.com/91002836/200172947-38106b65-37c9-4201-9ea1-b44bb0b729e5.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
色々起きてますね。

## BindingException

これは確かにmybatisのエラーのようですが、
いままで動いてたものが動かなくなるのはなぞですね。
mapper.xmlのディレクトリ構成でも変えたとか？
MapperインターフェースとMapper.xmlの関連あたりを見直してみましょうか。

いままで動いていたのならgitの差分で何を変更したのか見れると思いますし
まず影響がありそうな変更点を探るところからですかね。

## 最後のアラート

> 何度かvscodeを再起動したのですが、Gitとbuildエラーも表示されます。
> 関係ないかもしれませんが、これは放置していて大丈夫なのでしょうか。

これもそのままにしない方がいいでしょうね。
gitのexeへのパスがなくなったのかな？？
ひとつの方法は作業フォルダを再作成してみることでしょうか。
いま作業場所は退避するかして、git clone しなおしてみるということですね。

**Comment by yoko-Developer** [comment]
>mapper.xmlのディレクトリ構成でも変えたとか？

そんな危険なことはしていないです。

gitエラーは、調べたら解決できました。
buildエラーは解消しません。

前のバージョンをcloneしたら、当然ですが動きました。
buildエラーも表示しません。
テストコードのどこかがおかしいからエラーが出てるんですね。
[001]からやり直すしかなさそうでしょうか。。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> そんな危険なことはしていないです。

ですよねー。
せっかくのエラーなので私も一度見てみたいです。
忙しいでしょうけど、近々ZOOMで状況を見せて頂けますか？

**Comment by yoko-Developer** [comment]
ありがとうございます！
是非zoomでお願いします。
全く忙しくないです😃
