### ISSUE TITLE
importエラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#14]
#08バージョンに戻り（clone）#09 自動テストをやり直しています。
またエラーが出てしまいました。
buildエラーも出るのですが、無視して実行するとimportエラーと思われるエラー文が表示されてしまいます。。
`java.lang.Error: Unresolved compilation problems: 
 The import jp.co.planaria.sample.motocatalog.beans.SearchCondition cannot be resolved
 SearchCondition cannot be resolved to a type`

Mapperクラスでのエラーだと思うので、キャプチャ貼らせてください。
いつもながら全く間違えている気はせず、何度見直しても分かりません😢
再度cloneする方が早いとは思いますが、解決策を教えていただけますか。
![AFFB9007-B384-402E-9166-05BDE629087B](https://user-images.githubusercontent.com/91002836/201132342-abd3c914-29bc-4fb5-b3c9-2d7cf571a613.jpeg)
![E4B846D0-B326-4010-A988-B5AEA1105D33](https://user-images.githubusercontent.com/91002836/201132370-8fe165bf-26ea-4eb0-b496-8c7fbf7f563c.jpeg)
![214395A4-A93D-45A7-AD02-A4D69F1D2192](https://user-images.githubusercontent.com/91002836/201132548-e59c8783-81df-434c-a7b3-11925922d2d9.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

おっしゃるとおり`import`で起きているようですね。
`compilation problem`とあるし、リビルドしてみるのはどうでしょう。

vscodeはちょっと見づらい場所にリビルド機能があります。

↓javaのプロジェクトを右クリックすると現れるメニュー
![image](https://user-images.githubusercontent.com/22320079/201510124-73e566d5-e619-4e81-b626-04aa49b09a36.png)

**Comment by yoko-Developer** [comment]
リビルドして、解決することができました。
ありがとうございました。
