### ISSUE TITLE
【エラー】Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException

### ISSUE THREAD

**Issue by MizukaNagura** [HyunwookPark/question-box#16]
朴さん

初めまして。
名倉と申します。

質問を失礼いたします。
実行をすると、題名のようにエラー内容が出ます。

ブラウザには問題なく表示はされるのですが、気になりましたので質問しました。
内容は、ターミナルでデバッグ対象を起動できませんでした。という意味だと思うのですが、何かがおかしいのでしょうか？
<img width="1440" alt="スクリーンショット 2022-11-13 22 26 56" src="https://user-images.githubusercontent.com/85430680/201524905-0b1902bb-1bef-41d2-ad66-cd925f0113cb.png">

お忙しいところ恐れ入りますが、ご返信いただけますと幸いです。
よろしくお願いいたします。

**Comment by HyunwookPark** [comment]
@MizukaNagura 

ご質問ありがとうございます！
ご丁寧に挨拶ありがとうございます。　改めまして、朴と申します。

ご質問の内容ですが、私も発生したことがないのでちょっと調べてみました。
JDIの接続に関する例外のように見受けられます。

アプリの実行はできてブラウザからアクセスできるとのことですが、
JDIはJavaプログラムのデバッグをサポートする機能のようですので
デバッグ機能は使えなくなっているのかもしれませんね。

ソースコードのどこかにブレイクポイントをつけて止めることはできますか？
（↓こんな感じ）

https://user-images.githubusercontent.com/22320079/201529631-f353785f-2203-486b-94e0-025774e44f12.mp4

また、javaのデバッガーの設定やターミナルの設定はどんな感じになっているかも教えてもらうことはできますか？
![201529387-764cefc4-cc95-42c6-8603-2e1e3c268902](https://user-images.githubusercontent.com/22320079/201529990-f9d76f80-20a8-4d9b-ab43-0c6b973a1b7a.png)

**Comment by HyunwookPark** [comment]
@MizukaNagura 
長くご確認頂けていないようなのでクローズさせて頂きますね。
