### ISSUE TITLE
#9 テスト010について

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#18]
動画#9 の自動テスト、何日もかかりましたが遂に完走できました。
いくつか疑問点があります。
いつも通り初歩的すぎる質問ですが、よろしくお願いします。
テスト[010]
`assertThat(moto.getBrand().getBrandId()).isEqualTo("01");`
バイク情報取得で、SQLには`m_motorcycle.brand_id,`と記述されています。
`brand_id`ではなく`getBrand.getBrandId`と記述されていますが、
`getBrandId`のみではないのは何故でしょうか。

**Comment by yoko-Developer** [comment]
38:53辺りでServiceクラス、Mapperクラス、Testクラスを見比べていますが、何を確認しているのでしょうか。
見比べているだけで、特に書き換えるとかということがないように見えますが。
参考までに教えていただけますか。
よろしくお願いいたします。

**Comment by HyunwookPark** [comment]
> 何日もかかりましたが遂に完走できました。

おめでとうございます！！

> getBrandIdのみではないのは何故でしょうか。

`m_motorcycle.brand_id`はSQLで`テーブル名.カラム名`という書き方ですね。
それに対して、`moto.getBrand()`はMotorcycleクラスのフィールドとしてBrandがあって、
BrandクラスのフィールドとしてbrandIdがあるからですね。
仮にbrandIdがMotorcycleクラスのフィールドであればmoto.getBrandId()でもOKです。

**Comment by HyunwookPark** [comment]
> 38:53辺りでServiceクラス、Mapperクラス、Testクラスを見比べていますが、何を確認しているのでしょうか。

んー、ServiceクラスとMapperクラスを実装して、Testクラスを実行しているだけのように思いますね。

**Comment by yoko-Developer** [comment]
見比べは奥深いのですね！

ありがとうございます。
またすぐエラー宣言していましたが、早速すぎて低下＆詰みました。。
motocatalog.Mapper.xmlのSELECT文、44行目にm_mogorcycle.brand_idがあるので、単純に他のカラムと同じ記述でいいのかと思いました。
![77E51361-F239-4582-AACC-472D1012B28C_1_105_c](https://user-images.githubusercontent.com/91002836/203468391-92e1a420-4c34-4795-9e66-7d6927bd475c.jpeg)


MotoServiceTest166行目、MortorcycleMapper.xml44行目のbrand_idは、BrandMapper.xmlの8行目のbrand_idを参照している（取ってきている）ということでしょうか。
理解できなくてすみません。
よろしくお願いします。
![DD7757D7-2429-469C-8E10-C08B5F541324_1_201_a](https://user-images.githubusercontent.com/91002836/203469960-1e03c65a-003d-411a-88fc-7a64d1a3a3b3.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

MotorcycleMapper.xml

```xml
<select id="selectByPK" resultMap="motorcycleMap">
```

で書かれているresultMapによっと自動詰め替えをしているからですね。

```xml
    <association property="brand" javaType="jp.co.planaria.sample.motocatalog.beans.Brand" autoMapping="true">
```

これによって、`Motorcycle`の中の`Brand`のフィールドに値が詰め替えされています。

**Comment by yoko-Developer** [comment]
複雑でなかなか理解が難しいですが、じっくりソースと見比べて考えてみます。
一旦クローズさせていただきます。
