### ISSUE TITLE
#9 テスト011のエラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#19]
テスト[011]でエラー表示するところがあります。
Mapperクラスにメソッドを作成するというもので、`Create method...`をクリックするとエラーが消えると思います。
![161405BE-24AA-44D0-BF63-2DD859AFCF44_1_201_a](https://user-images.githubusercontent.com/91002836/202908425-abb39d1f-d5c1-47fc-bbdd-c0a9a1c40354.jpeg)

私のソースでは同じ箇所でエラー表示されていますが、エラーメッセージが違います。
どこかが間違えているのでしょうか。
Mapperクラスを修正したらエラーが消えましたが、気になったので教えていただけると嬉しいです。
![F84F69A6-61D3-4C87-AFB9-084F59283749_1_105_c](https://user-images.githubusercontent.com/91002836/202908620-54cdbc41-a300-4c86-97d4-7a1eaed5be3a.jpeg)
![A7C78350-C042-4546-99D7-3DFAAEB3AE2E_1_105_c](https://user-images.githubusercontent.com/91002836/202908626-6e339b63-f7a8-490c-b441-5018de3c4741.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
Mapperのメソッドがクラスメソッドかインスタンスメソッドかという点が原因ですね。
エラーの内容にも記載されているので再度確認してみてください。

合わせてクラスメソッド（static method）についても調べてみるとよさそうです。

**Comment by HyunwookPark** [comment]
- クラスメソッド: クラスの時点で利用できる動き。※インスタンス作らなくても使える
- インスタンスメソッド: インスタンスができてから利用できる動き

**Comment by HyunwookPark** [comment]
クラスフィールドを使ってみるとクラスとインスタンスの違いが感じられるかも。
ぜひお試しください。

**インスタンスからクラスフィールドを変更してみてください。**

```java
class Takoyakiki {
    static int color;
    int length;

    public void changeColor(int color) {
        color = color;
    }
    public void setLength(int length) {
        this.length = length;
    }
}
```

**Comment by yoko-Developer** [comment]
結構考えたのですが、わかりません。。
お時間ある時に教えていただけますか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
わかりました。
画面を見ながら答えをお伝えして少し解説を添えてみます。
「結構考えた」についてもどのように考えたのかそのときに私に伝えてもらえますか。

**Comment by yoko-Developer** [comment]
ありがとうございます。
よろしくお願いします🙇
