### ISSUE TITLE
テーブル定義書のI/O

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#2]
I=input
O=output
だと思いますが、添付した画面レイアウトで
①②③：入力するため「I」
④⑤⑥：表示されているため「O」
と解釈していますが、合っていますか？
参考にした記事では、私の解釈とは違うようです。
https://rainbow-engine.com/screen-desing-field-list/
![15A535A8-F474-485A-B5A3-686F0C9A70F3_1_105_c](https://user-images.githubusercontent.com/91002836/192523825-8a222e45-70d8-46d4-8d34-72aeaa03a11f.jpeg)

どう考えれば宜しいでしょうか？

**Comment by HyunwookPark** [comment]
最初の質問ありがとうございます✨

テキストボックスなどはインプット要素としてわかりやすいですね。

リンク先と認識が異なるのはボタンですね？
リンク先に記事の方は入力した情報をサーバ送るためのボタン、
つまり入力の目的のボタンなのインプットの扱いにしていますね。

@yoko-newDeveloper さんは、ボタンを表示しているからアウトプットと解釈されているようですね。

どちらが間違っているとは言いづらいですね。
結局はプロジェクトないでルールを決めて統一されればよいと考えます。


私の解釈を以下に書いてみます。

ボタンという要素自体を表示するのがアウトプットなら
テキストボックスという要素も表示しているのでアウトプットということになるから
ややこしいと考えます。

私ならボタンはインプットでもアウトプットでもないという表現の「-（ハイフン）」で表現します。

アウトプットは情報の値を「出力」している場合に使います。
ボタンは通常は値の出力ではないのでアウトプットとしては表現しません。

仮にボタン名に情報の値を出力させてボタン名が動的に変化するのであればアウトプットと表現してもよさそうです。

ボタンをインプットと表現するのも違和感があります。
例えば「検索ボタン」は検索条件を入力するためでもあり、
検索結果を出力するためでもありますしね。
多くのボタンイベントは入力をもとに出力するためのものなのであえて書くならI/Oになるかもしれません。
ただ、私は情報の値を入力するのか出力するのかを観点にしているのでどちらでもないという表現をします。

**Comment by HyunwookPark** [comment]
いい質問だなと思って長文になってしまいました。
理解してもらえたならクローズしてもらって、
議論を続けるか追加質問あればコメントくださいね。
(*‘ω‘ *)

**Comment by yoko-Developer** [comment]
お忙しい中、早々に回答してくださりありがとうございます🙇
いい質問✨嬉しいです！！

今回は、ボタンは「-」にしたいと思います。
別の画面のキャプチャを添付させていただきます。
「アウトプットは情報の値を出力」ということは、ラジオボタンが「O」になるのでしょうか？
違うとしたら、添付した「画面レイアウト」で、「O」はどれと考えれば宜しいでしょうか？
下記へ修正しました。（画面項目一覧の「I/O」列に記入）
何度もすみません。よろしくお願いいたします。
![7ACF7DB1-F980-4EA7-83B1-EA4BB45654F0](https://user-images.githubusercontent.com/91002836/192566486-4898b429-dcd1-4765-bbfb-3536022b8bfd.jpeg)
![2FF20C89-3910-48F4-8F94-B0C9C2A6B1AB](https://user-images.githubusercontent.com/91002836/192566516-a97d5c92-8bf8-4eb5-86c3-7bb3e04aa503.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
多くの入力欄はインプットがメインでしょうけど、
DBの値を入力済みで画面描画することも考えるとラジオボタンは「I/O」になりそうです。
プロジェクトによっては用途としてDBに保存するのが目的なので「I」と記載するルールにすることもありそうです。

## 整理するとこんな感じ

- 入力ではないテキスト表示なら「O」
- 入力のみでDB値使うことなければ「I」
- 入力 + DB値を入力済み描画なら「I/O」（多くの入力欄がこれに該当しそう）

ただし、プロジェクトによって考え方は異なるので
プロジェクト内メンバーが統一認識できて設計者と実装者の意思疎通に問題なければOK。

**Comment by yoko-Developer** [comment]
ドロップダウンのデータについてです。
日々使うアプリと考えると、ドロップダウンの方が手間がかからないかなと思いました。
年齢や生年月日、記録時間などは「数字」を選択
性別は「男の子」「女の子」

画面レイアウトと画面項目一覧には「見えるもの」しか書かないと思うのですが、見えない部分（ドロップダウンの選択肢）はデータとして記載すると思うのですが、どの設計書にどのように記載するのが良いでしょうか。

ドロップダウンとチェックボックスは「O」で宜しいでしょうか。（park&yokoチームの場合）

イベント仕様にドロップダウンの内容（データ）を記載しようと思いますが、大丈夫でしょうか。

**Comment by HyunwookPark** [comment]
> ドロップダウンについて

年齢、生年月日、記録時間などは「数字」をドロップダウンで選択するという意味ですね？
メインで利用するデバイスがスマホを想定の場合はそうかもしれませんね。
メインのデバイスをパソコンで考えるなら違う入力方法がより適切かもしれません。

性別はドロップダウンよりもラジオボタンの方が適切な気もします。
理由はラジオボタンの方が入力手間が少ないからです。

年齢・生年月日など選択範囲は多いものはラジオボタンとしては並べづらいので
ドロップダウンでよさそうです。

> 見えない部分（ドロップダウンの選択肢）はどのように設計書で表現するか

色んな表現方法がありますね。
プロジェクトによってもバラバラです。
以下に設計現場で見たことある記載方法を列挙してみます。

- 画面項目一覧の備考や出力内容欄を設けて選択肢をすべて記載する
- マスタテーブルに格納するとして画面項目一覧には対象テーブルのみを記載し、マスタテーブルのテーブル定義に選択肢を記載する
- イベント仕様に初期表示処理としてドロップダウンに表示する選択肢を記載する
- 補足資料などのシートを用意してドロップダウンの選択肢を記載する

> ドロップダウンとチェックボックスは「O」で宜しいでしょうか。

我々がチームとしてルールを作るなら。

ドロップダウンとチェックボックスは入力を目的としているので基本的には「I」で表現します。
ただ、更新画面などならDBの値を入力済みの状態で画面描画するなら「I/O」とします。

> イベント仕様にドロップダウンの内容（データ）を記載しようと思いますが、大丈夫でしょうか。

上記のとおり、その案もありです。
私なら項目一覧に表現するか、別途補足資料にドロップダウンの選択肢を書きます。
理由はドロップダウンは同じドロップダウンが色んな画面に登場する可能性があるからです。

**Comment by yoko-Developer** [comment]
ありがとうございます。
今、色々修正しているところですが、テキストボックスは「I/O」で良いと思っています。
「O」がひとつも無くなっているのですが、どのような項目が適切でしょうか？

必須項目についてです。
チェックボックスやラジオボタン等の選択項目で、いずれかの選択を必須にしたい場合の書き方が分かりません。
全ての値を必須をつければ宜しいでしょうか？（違う気がしますが。。。）

[設計書](https://docs.google.com/spreadsheets/d/1L62P8wcXuu4yLVlge5f2LSzG7n0D2PgN9qLm1g0PtFU/edit#gid=849875330)

![2844E96E-1A5D-4B04-97E6-FBB386B07AB0](https://user-images.githubusercontent.com/91002836/193442226-4315a775-4e59-46a1-81a1-124ddc2809d1.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> 「O」がひとつも無くなっているのですが、どのような項目が適切でしょうか？

別に無理に「O」にすることはないですよ。
記録の一覧を表示する画面なら一覧の項目が「O」になりそうですね。

> チェックボックスやラジオボタン等の選択項目で、いずれかの選択を必須にしたい場合の書き方が分かりません。

上記に貼ってもらった「画面項目一覧」のように「必須」の列に「Y」を表記することでよさそうです。
今はテキストボックスの必須項目に「Y」と表記していますが、
チェックボックスやラジオボタンも同様の表現でいいと思います。

**Comment by yoko-Developer** [comment]
@HyunwookPark 
無理に「O」は要らないんですね。
該当がありそうなら「O」にしてみます。

選択項目のどれか1つを必須にしたい場合、チェックボックスやラジオボタンのデータの全てを「Y」にすれば良いということで合っていますか。

先生のテーブル定義書を確認すると、データサイズが記載されていない項目があります。
intは記載しないというわけでもなさそうですよね。
そもそもVARCHARのサイズもよく分かっていないのですが、サイズを記載する場合としない場合の判断は、どのようにすれば宜しいでしょうか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> 無理に「O」は要らないんですね。
> 該当がありそうなら「O」にしてみます。

それでよさそうです。

> 選択項目のどれか1つを必須にしたい場合、チェックボックスやラジオボタンのデータの全てを「Y」にすれば良いということで合っていますか。

はい、そうしましょう。

> 先生のテーブル定義書を確認すると、データサイズが記載されていない項目があります。
> intは記載しないというわけでもなさそうですよね。
> そもそもVARCHARのサイズもよく分かっていないのですが、サイズを記載する場合としない場合の判断は、どのようにすれば宜しいでしょうか。

INTやDATETIMEは桁数が決まっているので設計書上はなにも記載していませんでした。
VARCHARは桁数が決まっていないので必要な桁数を設計したというわけですね。

**Comment by yoko-Developer** [comment]
テーブル定義書の「データ型」と「サイズ」の入力について、質問させてください。
ラジオボタンとボタンの項目は、どのように記載すれば良いでしょうか。
選択項目が記号、文字列、数値とありますが、選択するデータ（画面に表示される内容）に合わせて入力するのでしょうか？
Iの「食欲」の項目は、記号＋備考（長い文字列）なのですが、備考に合わせて設定してよろしいでしょうか。

イベント仕様の書き方が分かっていません。。
併せてご確認（レビュー）していただけますか。

今日修正した箇所は黄色でマークしています。
他にも変更した箇所があると思うので、よろしくお願いいたします。

[drow.ioER図・画面遷移図・画面レイアウト](https://app.diagrams.net/#G1ycqmTab-LakzbwMuW3eKVXcmps3e4wWH)
[スプレッドシート画面一覧・イベント仕様・画面レイアウト](https://docs.google.com/spreadsheets/d/1L62P8wcXuu4yLVlge5f2LSzG7n0D2PgN9qLm1g0PtFU/edit#gid=693814024)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
#13 と一緒にZOOMで見てみましょう～

**Comment by yoko-Developer** [comment]
ありがとうございます！
よろしくお願いします。
