### ISSUE TITLE
「;」の有無について

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#20]
YouTubeや書籍を見ながら、Vue.jsの学習をしています。
全く同じソースではありませんが同じと思われる箇所に、YouTubeでは「;」がありますが、書籍では記述がありません。
22行目の「;」を削除してもエラーにならず、実行結果が同じです。
下らない質問ですみません。どちらが正でしょうか。
![3F69FC59-0B22-4BC9-8069-17212C2E1763_1_201_a](https://user-images.githubusercontent.com/91002836/202909211-1eddc12b-6460-4d94-b8b2-8e575a0c4a02.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
いい質問ですね。
どちらも正です。^^

Javascriptにはセミコロンを省略できる記法がありますので
書いても書かなくても動きます。
ただ、アプリケーションとしてどちらに統一するかは決めておくのがよさそうですね。

ちなみに私は最近省略するルールを採用しています。

**Comment by yoko-Developer** [comment]
いい質問😳
ありがとうございます！！
どちらでも大丈夫なんですね。
「,」は打たないとエラーになるので、どうなのかなと思いました。

統一して学習していきたいと思います😀
