### ISSUE TITLE
アプリを実行できない

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#21]
テストの次の章の最初の、アプリを起動するというところです。
まずbuildエラーが表示されました。
問題を修正した後、このプロジェクトをリフレッシュしてビルドしてみてください。
![6EF53959-9FF8-4B05-B9A6-8FD22F61B3E3_1_105_c](https://user-images.githubusercontent.com/91002836/203314984-a0873c75-02e2-4d3d-bc39-e7c3e87dde2a.jpeg)

無視して実行したところ、エラー表示されました。
エラー: メイン・クラスjp.co.planaria.sample.motocatalog.MotocatalogApplicationを検出およびロードできませんでした
原因: java.lang.ClassNotFoundException: jp.co.planaria.sample.motocatalog.MotocatalogApplication
MotocatalogApplicationを確認しましたが、
![E339C2ED-9B2B-42A4-BC35-8D794D545A12_1_201_a](https://user-images.githubusercontent.com/91002836/203315349-c348711a-1f8a-4b87-877e-e8ceae2ceecf.jpeg)

調べるとビルド出力をクリアして初期化して再構築するというのが該当しそうですが、どうしたら良いのか分かりません。
いつもすみませんが、よろしくお願いします。

**Comment by HyunwookPark** [comment]
大事なエラーメッセージは`The project was not due to "Resource already exists on disk: '~.DS_Store'.".`あたりのように思います。
Macの`.DS_Store`ファイルに関する記事を探してみてはいかがですか？

**Comment by yoko-Developer** [comment]
前にも.DS_Store問題があったのを覚えています。
[この記事](https://ios-docs.dev/ds_store/)を参照し、下記コマンド実行しました。
`sudo find / -name ".DS_Store" -delete`
`Killall Finder`

![9906EC67-8312-4C50-9016-B3A1C98BA740](https://user-images.githubusercontent.com/91002836/203476326-142685c6-de30-42bf-82f6-ec359a783b16.jpeg)
![B63154F4-8994-4E33-9D3D-947C0A7CD47A](https://user-images.githubusercontent.com/91002836/203476493-8d18b031-51c4-420e-8db7-052ed6c326b4.jpeg)


無事に.DS_Storeは削除できたのを確認しましたが、違うエラーが表示されました。
やはりリフレッシュが必要なようですが、方法が見つけられません。
![64EDF41E-A8A6-4BC0-9D20-213090022FCF](https://user-images.githubusercontent.com/91002836/203476976-382787b8-45bd-46b1-bc4d-f5d880a1ce4d.jpeg)
![63639558-82C9-4271-90DA-93F9155B8F60](https://user-images.githubusercontent.com/91002836/203477011-3e13c53a-709c-4dd3-a61e-980d345d4b02.jpeg)


試しにeclipseで実行したら、問題ありませんでした。
![E2213B38-35CD-49DF-9123-50FEE7CF8915](https://user-images.githubusercontent.com/91002836/203477364-00c58a3b-ee4e-4b27-9fbd-1e341fa9f1fe.jpeg)
![212A3F57-6BE8-4407-B2C5-BB18BC78AFC7_1_201_a](https://user-images.githubusercontent.com/91002836/203477398-0602fbbb-5f1b-4eb7-a962-bda7dcd6f02c.jpeg)


vscodeの再起動では改善せず、macを再起動したら動いてくれました😂
vscodeのリフレッシュ方法を探したら`Cmd + Shift + P` で`Clear Editor History`実行のようですが、改善しませんでした。
他に方法があれば、教えていただけますか。
とりあえず、次に進めそうです。
いつもありがとうございます😀
