### ISSUE TITLE
ブランチの修正方法

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#22]
動画#11でpushをしたところ、`git push --set -upstream or origin・・・`が表示されないのでおかしいと思ってSourceTreeを確認しました。
最新がローカルとリモートで並んでいたので、そのままmergeしました。
![A4EB1A86-B285-4850-B964-028821C55CA4_1_201_a](https://user-images.githubusercontent.com/91002836/204142072-39661c50-03e1-433f-a250-c5ea522d3e56.jpeg)

ブランチ名feature/#15_delete_ds_store
前回コミットメッセージを間違えて修正したところなのですが、修正前のコミットメッセージが保存されています。
1コミット先行　1コミット遅れと表示されていて、マージされていない状態（？）のようです。
[このブランチ](https://github.com/yoko-newDeveloper/motocatalog/tree/feature/%2315_delete_ds_store)にcheckoutして、pushしたら良いのでしょうか。
少し前のブランチのコミットメッセージを修正したいのですが、その場合どうしたら良いのか教えていただけますか。
![BFCB6A00-6833-4F6B-A49C-F087ED8928B5_1_201_a](https://user-images.githubusercontent.com/91002836/204142110-7f4fbe44-5a39-4fed-a936-e20cf594778a.jpeg)

**Comment by yoko-Developer** [comment]
pushした時に`A build file was modified. Do you want to synchronize the Java classpath/configuration?`
ビルドファイルが変更されました。Javaクラスパス/構成を同期させますか？と聞かれていますが、yesで良いのでしょうか。
メッセージは無視していると消えますが、無視で良いのでしょうか。

**Comment by HyunwookPark** [comment]
もうコメントの変更はできたとのことでしたので、
本日zoomでお伝えしたことを書いておきますね。

コメントを変更したコミットをリモートブランチに反映するなら
強制プッシュで反映できます。

ただ、現状はおすすめしません。（放置をおすすめします）

現状のmainブランチが対象のブランチとほかのブランチをマージした状態で
ずいぶん先に進んでいる状態のようですね。
なので対象のブランチがmainからずれるような感じになりそうです。
mainを対象のブランチのコミット前まで戻してほかのブランチもマージしなおす方法も
考えられますが労力に見合う作業ではないように思います。

いまは一人で作業しているのでいくらでもできますが、
実際の現場のgitならほかの人のブランチもマージした状態の可能性もありますよね。

つまり、現状のまま放置しましょう。^^

でも一度無理にでもチャレンジしてみるのは経験値にはなりそうです。

**Comment by HyunwookPark** [comment]
> pushした時にA build file was modified. Do you want to synchronize the Java classpath/configuration?

このメッセージはどんな部分に出てくるのか再現できるならまた見せてほしいです。

**Comment by yoko-Developer** [comment]
再現したら、お知らせします。
