### ISSUE TITLE
rails assetsコンパイル時のwarning

### ISSUE THREAD

**Issue by shipo3** [HyunwookPark/question-box#23]
初めまして！RaiseTech（Javaコース受講生）の内山と申します。
yokoさんから後押しいただきまして、初めて質問させていただきます。よろしくお願い致します！
現在、Javaを終了後、AWSを学習中なのですが、RailsアプリをCloud9においてデプロイする課題に取り組み中です。
（アプリは講師の方が作成されたものをgit cloneしています。）
アプリまでは繋がっても「asset pipeline」のエラーが出まして、アプリが表示されませんでした。。

![アセットパイプラインのエラー](https://user-images.githubusercontent.com/100467635/205428909-cafe2d9c-7637-41fb-ae81-e23fe2fb7d20.png)

その後　`rails assets:precompile`　にて存在していなかった「application.css」が作られるようにできまして
アプリ表示・操作もできるようになったのですが、**warningは残っている状態です。**
以下画像に表示されているwarningはそのままでも問題ないものでしょうか？

①「warning ../../package.json: No license field」
②「The value 'hashed' for option 'optimization.moduleIds' is deprecated. Use 'deterministic' instead.」

![rails assetsコンパイル時のwarning](https://user-images.githubusercontent.com/100467635/205428864-80740213-c78c-458e-bf59-7f3b2882ddd8.png)

ーちなみにー
①はpackage.jsonファイルあったので　"license": "UNLICENSED"　を追記してみたのですが
「Unexpected string in JSON at position 694".」エラー出ましたので消しました。。

お時間ある時に、ご確認いただけると幸いです。
よろしくお願い致します！

**Comment by HyunwookPark** [comment]
@shipo3 
ご質問ありがとうございます。
yokoさんからお聞きかもしれませんがRubyやRailsの方はさっぱりわからないです。
そのうえでのアドバイスなのでお役に立てるかわかりません。

急ぎであればスクール内の講師やメンターさんに支援を求めてみてくださいね😉

**Comment by HyunwookPark** [comment]
## まず

一般的にwarningは放置でもおおよそ動きますが、放置してよいというものではないですね。
特定の機能を利用する場合やリリース時に困ったり、不具合の可能性があったりします。
至急ではないですが、早期に対応しておく方がいいですね。

他の学習が進まなくて困るぐらいなら放置して進めればよさそうです。
すぐに解決できなさそうなら、状況や試したこと記録しつつ合間合間に色んな解決方法を試すことをおすすめします。

試したこととその結果を記録し、参考にしたサイトのURLなどを残すとよいでしょう。

## 仮説

参考的に講師の方が作ったアプリのため細かいところまで作ってない可能性もありますし、
講師の方が作ったタイミングよりもろもろのバージョンが上がったため状況が変わった可能性も考えられますね。

## ①について

> ①「warning ../../package.json: No license field」

`"license": "UNLICENSED"`設定時、`Unexpected string in JSON at position`の続きは`parsing~`と出ましたか？

## ②について

> ②「The value 'hashed' for option 'optimization.moduleIds' is deprecated. Use 'deterministic' instead.」

こちらは`optimization.moduleIds`のオプションで`hashed`は非推奨で、`deterministic`を使うように書いてますが思い当たるところはありますか？
webpack.config.jsというファイルはありますか？

## 私が見たサイト

- ①
    - https://qiita.com/dropout26/items/0ace9fce0e909b733623
    - https://qiita.com/kozakura16/items/ebaf8ea58fc49dcbdd73
    - https://qiita.com/narimiya/items/fe0e308a2177c9f0e275
- ②
    - https://webpack.js.org/configuration/optimization/#optimizationmoduleids
    - https://qiita.com/irico/items/66615f07426e5d885555

**Comment by shipo3** [comment]
@HyunwookPark 
お忙しいところご回答いただきありがとうございます！！
本日残業にて、確認遅くなりまして申し訳ございません。
yokoさんに質問はなんでもOKと伺っていましたので、失礼いたしました💦
仮説を考えていただいて恐縮です。

①②について、いただいたリンクも参照しながら再度確認してみます！
今後ともよろしくお願い致します。

**Comment by shipo3** [comment]
夜分遅くにすみません。。
共有いただいたサイトを確認しまして、修正してみたところ
**②のwarningは消えました！**
![WARNING消える](https://user-images.githubusercontent.com/100467635/205675060-89937abb-6fbc-4bda-bb10-549074e4f7d2.png)

①は`"license": "UNLICENSED"`設定時、`Unexpected token { in JSON at position 694`　が表示されました。
「694」とは何か？？
「Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.」に記載のURLに訪れてみましたが
解決できませんでした。。。

![①のエラー](https://user-images.githubusercontent.com/100467635/205681089-14a9d980-99e4-46be-95db-61390797edbb.png)

お手数をおかけしますが、何かヒント頂けましたら幸いです。
お時間あるときに、ご確認よろしくお願い致します！

**Comment by HyunwookPark** [comment]
@shipo3 

> ②のwarningは消えました！

ナイス👍

**Comment by HyunwookPark** [comment]
@shipo3 

> 「694」とは何か？？

おそらく、`package.json`の正しくない記述個所の行数と思われます。
`package.json`にはどのように記述したのか見せて頂けますか。

**Comment by shipo3** [comment]
@HyunwookPark 
ご確認いただきありがとうございます！
package.jsonには27～29行目に「"license": "UNLICENSED"」を追加致しました。
全体でも30行目までですので**「694」**が何を指しているのか？？と思っています。

![package](https://user-images.githubusercontent.com/100467635/205929859-12ed38d9-dc16-4e13-a4b9-b807d6c2b0fc.png)

　↓
1つ前の｝にカンマがありませんでしたので、追加してみたところ**「695」**に変わりました。

キャプチャーを添付させていただきます。
お手すきの際に、ご確認の程よろしくお願い致します。

![番号変わる](https://user-images.githubusercontent.com/100467635/205929054-d49a9988-3b3e-41f8-a61e-6fd6d38b0d63.png)

**Comment by HyunwookPark** [comment]
@shipo3 
返事遅くなりました。
`package.json`の「,」の気づきはいいですね。

```json
    },
    {
        "license": "UNLICENSED"
    }
}
```

ではなく、

```json
    },
    "license": "UNLICENSED"
}
```

こんなふうに書いてみるのはどうですか？

**Comment by shipo3** [comment]
@HyunwookPark 
お忙しいところ、ご回答いただきありがとうございます！
最後のエラーも消えました！
なるほどです。　他の部分を見ても
「｛」は　「：」の後にありますので、子要素（？）がなければ｛｝で囲む必要ないのですね！

![最後のエラーも消えた](https://user-images.githubusercontent.com/100467635/206895850-29a9b57d-c5c8-438f-8e7b-8ce4dce584cf.png)

設定内容がOKであれば、記号やインデントなどに注目するようにしたいと思います！
「695」などは行番号でなくて、文字数のことでしょうね。
記事の探し方とか、チェックポイントなど・・勉強になりました。
ありがとうございました！！お手数をおかけしました。。

**Comment by HyunwookPark** [comment]
@shipo3 
エラーだったのはjsonの文法上のことだったので書き方を変えてもらった次第です。
ライセンスのワーニングも消えてほしかったのですが、
"license"の設定が効果を発揮していないようです。

お役に立てずすみません。

**Comment by shipo3** [comment]
@HyunwookPark 
ご確認ありがとうございます！
そうなのですね。JSONの　文法の問題なのですね。
ちょうど色々調べているときにJSONの書き方についてもまとめたい！と思っていたところでした。

お時間いただきましてありがとうございました！
また、ご意見いただきたい時に質問させていただくかもです。よろしくお願い致します。
＊本issueはクローズさせていただきます。
