### ISSUE TITLE
グリットシステムの日時の場所

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#24]
Bootstrapを使って、日時をグリットシステムの右側に寄せたいのですが、何故か2行になってしまいます。
`col-2`の-2を削除すると左に戻りますが、1行で表示されます。
どうしたら良いのか教えていただけますか。
よろしくお願いいたします。
![1F8AFBA2-A3C0-4A90-91C8-BF3AA07EE269_1_201_a](https://user-images.githubusercontent.com/91002836/205498529-7366aa3c-0f8c-449b-9864-3bd73f0c35f6.jpeg)
![34F201D4-F799-4717-934D-9112E88412AF_1_201_a](https://user-images.githubusercontent.com/91002836/205498542-87d39cce-6bcb-4a05-ace5-49c87c055133.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
bootstrapはレスポンシブデザイン対応になっていて、
モニターのサイズに合わせて各要素のサイズが変わります。

見たところ、ウィンドウのサイズが小さいみたいなので、
大きいモニターで全画面にしてみてください。

私もウィンドウサイズを縮めると↓こうなります。
![image](https://user-images.githubusercontent.com/22320079/205531139-460be7eb-5348-4be9-84c0-cd8a908446bd.png)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

試しに`<div class="col-2 col-sm-3">`としてみてください。
グリッドシステムは画面サイズに合わせてレイアウトを変化されるための仕組みがあります。

ここも参考にしてみてください。
https://getbootstrap.jp/docs/5.0/layout/grid/#grid-options

**Comment by yoko-Developer** [comment]
画面サイズについては、私も真っ先に疑いました。
最大化しましたが、27インチモニターでもmacでも変わりませんでした。
![1470F221-78F7-4751-AC33-F3222A30C01B](https://user-images.githubusercontent.com/91002836/205623021-4dafac81-577a-43ff-9530-f1a2b86f10f9.jpeg)

`<div class="col-2 col-sm-3">`　を実装し、無事に1行になりました！！
`col`って「列」ですよね？
`col-sm-3`とは、縦幅を狭くするということでしょうか。
そもそも`col-2 `って何でしょうか。
`col-sm-3`数字を変更すると左右に寄る
`col-2 `数字を変更しても変化なし
単体だとやはり左右に寄りました。
教えていただけると嬉しいです。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

`col`は列のことですね。
`col-`の後ろについているのが画面サイズを表しています。
`sm`とか`md`とか。

各サイズのときに何列分にするのかという指定になります。

![image](https://user-images.githubusercontent.com/22320079/205785960-2044cdc4-ae7a-4b5d-ad2c-6d8467efe446.png)

上記コメントに貼ったURLに詳しく書いてますのでまた見てみてください。↓こちらにも貼っておきます。
https://getbootstrap.jp/docs/5.0/layout/grid/#grid-options

**Comment by yoko-Developer** [comment]
ありがとうございます。
色々やってみます！
