### ISSUE TITLE
vscodeのショートカットキー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#25]
調べても分からなかったので、質問させてください。
パク先生が選択している状態から一気に文字を入力しているのですが、どうやっているのかどうしてもわかりません。
`Shift + ⌘`だと短冊選択になって、違う場所が選択されてしまいます。
こんな質問で申し訳ありません。
![A3F9ECC1-30C3-478D-B418-D4F1492DB634_1_105_c](https://user-images.githubusercontent.com/91002836/205498724-befe69a2-2327-4b1d-9c9b-db404fade580.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

Windowsだと`Ctrl + D`でやっています。
Macだと`Cmd + D`でどうですか？

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

`Eclipse Keymap`という拡張機能が`Cmd + D`を行削除機能として上書きされてましたね。
拡張機能削除で解消してよかったです。
私も勉強になりました。

**Comment by yoko-Developer** [comment]
ありがとうございました。
これでかっこよくvscodeが使えるようになりそうです😃
