### ISSUE TITLE
git pushのエラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#27]
git pushの途中でターミナルが消えてしまいました。
git statusすると下記エラーが表示しました。
```
On branch #25_create_update_page
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/main/java/jp/co/planaria/sample/motocatalog/beans/Motorcycle.java

no changes added to commit (use "git add" and/or "git commit -a")
```

一応調べると、`git add`が必要とのことで、再度
`git add .`
`git commit -m" 更新画面をデザインした"`

Githubを確認すると、同じコミットが2つあります。
![347D41F8-9EC9-43E0-BB50-6668CC952E5E_1_201_a](https://user-images.githubusercontent.com/91002836/206857294-340ccd54-96f7-45fe-93e1-cfdf6dc7ec28.jpeg)

ひとつコミットを削除したくて
`git reset --soft HEAD^`

消えてないので再度
`git reset --soft HEAD^`

`git push`
エラー

余計な操作をすると、どんどん深みにはまっていきそうです。
どうしたらよろしいでしょうか。
よろしくお願いいたします。

![619F09D0-57EF-4B18-BB9D-763B7BB8F647](https://user-images.githubusercontent.com/91002836/206857748-c4975908-821f-47c3-b833-50d37a275344.jpeg)

![1C80F0CF-8FB9-445B-A25C-7E85C08E20C9](https://user-images.githubusercontent.com/91002836/206857746-e16484d5-90d7-47cb-a84d-93c9906b4d0a.jpeg)

**Comment by yoko-Developer** [comment]
カレントをmainブランチにしてpull
もう一度
```
git reset --soft HEAD^
push
```
で大丈夫でしょうか。
ローカルの方が遅れているので、リモートからpullして重複しているコミットを削除、pushで良いかなと思っています。
違うでしょうか。。

**Comment by yoko-Developer** [comment]
私の仮説は失敗に終わりました。。
2枚目の画像と同じエラーが表示しました。
SourceTreeを確認したら、プル2　コミット2です。
`feature/#25_dataformat_alignment`ブランチをカレントにしようとしたら、エラー表示しました。
![63D33865-5921-42AF-B4B9-CFEC0E5D109E_1_201_a](https://user-images.githubusercontent.com/91002836/207033312-d7510781-8285-4cdc-94e6-e2f697394a8c.jpeg)

プッシュを押したら、ターミナルと同じエラーが表示されてしまいました。
![207225DE-66ED-41DD-B6CB-3B37FB10D07B_1_201_a](https://user-images.githubusercontent.com/91002836/207034817-7f02ad0a-89fc-42ff-a1a8-a052f5a88e7c.jpeg)



プルしたらうまくmergeできたように見えますが、プッシュ1となっています。
再度pushを押しても変わりません。
![8E214A55-329F-4B53-8E81-A9F5D8721862_1_201_a](https://user-images.githubusercontent.com/91002836/207035141-e2be65ad-6fec-41df-97ef-b93dbfcf420b.jpeg)

`git push`しても`Everything up-to-date`
プッシュ1ですが、このままで大丈夫なのでしょうか？



GithubのPull requestsタブを押すと、画像の画面になります。
Create pull requestは押しても反応がありません。
そもそも、プッシュ1のままでPRしても良いのでしょうか。

![5201D8F5-5BB2-44D6-828C-214433DE5F1D](https://user-images.githubusercontent.com/91002836/207036805-0e3a5d3e-1e23-4dde-b031-bf5175318882.jpeg)


pushした後でgit commitを削除することはできますか。
forkですが、mergeしても良いのでしょうか。

**Comment by yoko-Developer** [comment]
解決しました。
PR→mergeできました。

**Comment by yoko-Developer** [comment]
mergeまでおわったのですが、コミットが3つになってしまいました。
PR後にコミットを削除することはできますか？
調べたところ「できない」という記事にしか出会わないので、教えていただけますか。

![18097B1B-0887-4767-8AD8-372672A3F22B_1_201_a](https://user-images.githubusercontent.com/91002836/207600234-b3c7b2a6-a226-4146-8d9a-3c42c4b48db7.jpeg)

**Comment by yoko-Developer** [comment]
PR、mergeは無事に終わったのですが、issueが残っているように見えます。
issueを紐づける操作は忘れずに実施したつもりです。
紐付けに失敗しているのでしょうか。
だとしたら、今から紐づけることはできませんか。
https://github.com/yoko-newDeveloper/motocatalog/issues
![98F976EB-0BE6-403E-8A2E-62D635E8154F](https://user-images.githubusercontent.com/91002836/207604858-388f933f-8204-4fba-b7f0-a72b5410a56c.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> だとしたら、今から紐づけることはできませんか。
紐づけはあとからできます。

ただ、issueが関連付けされた状態でpull requestをマージすると自動的にissueもクローズされますが、
この場合はissueがクローズされずに残りますので手動でクローズすればOKです。

**Comment by HyunwookPark** [comment]
> mergeまでおわったのですが、コミットが3つになってしまいました。
> PR後にコミットを削除することはできますか？

コミットをまとめる方法はありますよ。以下のなどを参考にしてみてください。
https://dev.classmethod.jp/articles/git-commit-matomeru/

ただ、マージしたあとならマージした先のブランチも整理する必要があるので
おすすめはしないです。

どうしてもまとめるなら、リセットと強制pushと組み合わせることでコミットをまとめることができます。

**Comment by yoko-Developer** [comment]
今回はこのままで諦めます。
共有していただいた情報は、色々やり方があるということで学習させていただきます。
ありがとうございました。
