### ISSUE TITLE
コンソールでのテスト

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#28]
jsを使っていると、よく`console.log`で、ブラウザ実行する前にテストしながらソースを書いているようです。
まだ使い方は分かっていないのですが、Javaでもそういう書き方があるのでしょうか。
テスト用にファイルを作って`console.log`で試しながらアプリを作っているようなので、使い方を覚えたいと思っています。
質問の意味が分からなければ、申し訳ありません。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
jsの`console.log()`にあたるものはJavaでは`System.out.println()`ですね。
ただ、標準出力は業務ではあまり使いません。
ブラウザで使うjsの場合はログ出力の概念がないのでconsole.log()を使っているという現状です。

Javaではログ出力でデバッグや運用に必要な情報を出力します。
その方法は動画あるSLF4Jを利用してログ出力している部分がそれにあたります。
よって、必要な情報は`log.info()`などで出力しましょう。
デバッグなら`log.debug()`を使いましょう。

デバッグでログ出力する場合、以下の2つの観点で私はログを仕込みます。

- 変数に入っている値を確認したいとき
- 処理がどこまで進んだか確認したいとき
    - 例外発生時はtry{}のどこかで例外が発生したはずなので、どこまでは正しく動いたのか確認したりなど
        - try{}の上から明らかに動いている処理には仕込まず、分岐・ループ・計算など例外発生原因の可能性がある部分の少し手前あたりに仕込みます。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

デバッグ用途であればIDEのデバッグ機能を使うとよいですが、
本番環境であればデバッグ機能は使えないので
このテクニックは知っておくのがいいですね。

また、ログ出力はデフォルトの場合、コンソール（標準出力）に出力されます。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
ログには「ログ・レベル」という概念があって、
application.ymlに書かれたログレベル以上のログの種類が出力されます。

**Comment by yoko-Developer** [comment]
ログ・レベルについて、初めて知ることができました。
デバックとか例外とかは理解が乏しいので、これから少しずつ学習していきます。
ありがとうございました。
