### ISSUE TITLE
デザインパターン

### ISSUE THREAD

**Issue by otowmoyarng** [HyunwookPark/question-box#3]
https://www.techscore.com/tech/DesignPattern/

どれが好きですか？
またバッチならこれ、webならこれみたいなお決まりパターンあったら教えて欲しいです
よろしくお願いします

**Comment by HyunwookPark** [comment]
Singletonを除き、
通常の業務ではこれらのパターンは使わなくていいかなと思います。

昔はかっこよく感じましたが、
今ではできるだけシンプルな作りがいいかなと思うようになりました。

Singletonは用途があまりに明確なのでちょくちょく使います。
わかりやすい点においても好きなパターンのひとつです。
Singletonはエンジニアなら知っておいてほしいパターンですよね。

Facadeパターンは昔よく使ったパターンですね。
他にもいくつか使ったことがありますが大した効果はなかったと感じています。
私の使い方やチームへの普及がよくなかったかもしれませんが。

バッチでもWebでもなく、
共通部品やフレームワークの制作の場合はこのような
パターンを活かせるタイミングがありそうです。
ただし、それでも利用は最低限に留めるのがいいと思います。
後任のエンジニアがメンテナンスしやすいのがいいと思います。

業務では使ったことありませんが、
個人的な趣味で「Observerパターン」が好きです。
初めて見たときカッコイイな！と思った記憶があります。

**Comment by HyunwookPark** [comment]
@otowmoyarng 以降の議論やメッセージがなければクローズしちゃってください。^^

**Comment by otowmoyarng** [comment]
@HyunwookPark 
Observerパターン初耳ですが、これいいですね。
なんかあったら設計してみようと思います

ご回答ありがとうございました。
