### ISSUE TITLE
vscodeでの新規作業フォルダ作成方法

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#30]
非常に初歩的ですが、質問お願いします。
vueの学習をしたくてプロジェクト作成したいと思っていますが、うまく行きません。

【やりたいこと】
vscodeで新規作業フォルダを作成する
作業フォルダパス：ドキュメント
作業フォルダ名：vue

【やったこと】
・手順1
ファイルダブ→open folder→ドキュメント→vue→フォルダを選択
・手順2
ファイルタブ→open folder→ドキュメントにあるvueフォルダのパスコピー→パスを貼り付ける
・手順3
ファイルタブ→open folder→ドキュメントにあるvueフォルダをGetStartスペースにドラッグする
・手順4（作業フォルダを作成せずに実行する）
ファイルタブ→open folder→ドキュメント→新規作成→フォルダ→vue→フォルダを選択

【実行結果】
・手順１〜３：無反応でEXPROREに何も表示されない
・手順４：パスが存在しませんと表示
以前はいつもこの方法で実行できていたと思うのですが、手順が間違えていますか？
拡張子が必要とかでしょうか。（フォルダ作成するだけなので不要と思っています）

新規作業フォルダの作成の方法を教えていただけますか。
お忙しいところすみません。
よろしくお願いします。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

フォルダを作って開くだけなら、どれでもよさそうですけどね。
`GetStartスペース` はなんのことかわかりませんけど、なんとなくやりたいことはわかります。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
MacならFinderでフォルダを開いて右クリックで「VSCodeで開く」みたいなのができませんか？

またはターミナルでフォルダ移動したあとにパスの部分をクリックはどうですか？
WindowsだとCtrl + 左クリックなのでMacだとCmd + 左クリックかな？

![image](https://user-images.githubusercontent.com/22320079/211183551-b80d709e-581a-4cfe-a629-c0869b6a53b4.png)

**Comment by yoko-Developer** [comment]
>MacならFinderでフォルダを開いて右クリックで「VSCodeで開く」みたいなのができませんか？

Windowsもmacも表示されません。。
macだと新規作成できるのですが、Windowsだとできなくて。
macの場合、下記手順で作成しています。
![vscode新規ファイル](https://user-images.githubusercontent.com/91002836/211185496-f023e418-1566-435b-aee5-a74d40a77939.gif)

**Comment by yoko-Developer** [comment]
macにはエクスプローラに「vue」フォルダがされました。
Windowsだと何も表示されません。


![B4439885-C36D-446E-9473-1EB3F66F5E08_1_201_a](https://user-images.githubusercontent.com/91002836/211185625-8b545b23-856f-4f83-9f28-03ef12b182d8.jpeg)


試しにカレントディレクトリを「vue」のある場所に移動し、同様にドラッグしてみました。
Windowsの場合は、エクスプローラにフォルダ名が表示されないのでしょうか？

**Comment by yoko-Developer** [comment]
フォルダ名が表示されなくてもプロジェクト作成できていました。
おそらくWindowsの仕様ということのようですね。
ありがとうございました。
