### ISSUE TITLE
push後のGithubブランチについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#31]
【現在の状況】
・エラー解消対策のため、一旦エラーが出ている状態でブランチ1をpushした。
・ローカルでブランチ1を修正してエラー解消。

【自分の見解】
①ブランチ1はリモートとローカルに差分があるため、このまま開発を進めるとコンフリクトを起こす。差分を無くする必要がある。
②変更してpushしたファイルは、GithubのリポジトリからコピペすればOK。

【やったこと】
・ブランチ1の変更箇所を戻す。（①のため）
・カレントブランチをmainに変更。
・リモートmainをpull。

【現在の状況】
・htmlがファイルごと無くなってしまった😭

【質問・悩み】
②を実行したら、エラーだらけになってしまいました。
私の考えが間違えているのでしょうか。
そもそも①から違いますか？
クローンしても全てのファイルが持って来れず、困っています。
せっかくここまで進んだので、アプリを完成させたいと思っています。
よろしくお願いいたします。

**Comment by yoko-Developer** [comment]
もう一度考えたのですが、あのまま作業中のブランチで開発を続け、終わったらcommit→pushで良かったですよね？
おかしなことをして、35個もエラーが表示してしまいました。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> ②を実行したら、エラーだらけになってしまいました。

②とは↓これのことですね？実行とは変更してpushしたという話のことですか？

> ②変更してpushしたファイルは、GithubのリポジトリからコピペすればOK。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
すみません。
何度も読み返したのですが、
話の流れがぼやけて解釈や判断が難しいです。

前提を明確にしたり、「このまま・あのまま」を明確にしてもらえると助かります。

- 【現在の状況】が2つあるけど、時系列ですか？両方現状ですか？
- HTMLが消えたとはローカルで消えたということですか？リモートリポジトリで消えたということですか？
- `②を実行したら、` とありますが、【自分の見解】は見解ですか？実行したことですか？
- エラーが出ていたのはjavaのファイルですか？htmlのファイルですか？
    - htmlファイルを編集していたから消えたということ？

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

作業中のブランチでエラー解消したけど、
コンフリクトが気にるのでpushはしていないということですね？
その作業中にhtmlファイルが消えたという意味でしょうか？

**Comment by yoko-Developer** [comment]
謎の質問をしてすみません。
>【現在の状況】が2つあるけど、時系列ですか？両方現状ですか？

質問してから操作を試みたので、時系列となっています。（投稿を削除できなかったため）

>HTMLが消えたとはローカルで消えたということですか？リモートリポジトリで消えたということですか？

ローカルから消えてしまいました。
リモートには存在しているので手動で作成（内容はコピペ）しましたが、うまくいきませんでした。

>②を実行したら、 とありますが、【自分の見解】は見解ですか？実行したことですか？

自分の見解（②）は実行済みです。

>エラーが出ていたのはjavaのファイルですか？htmlのファイルですか？
htmlファイルを編集していたから消えたということ？

クローンしたらhtmlファイル自体がクローンできていなかった状況です。
エラーは、Javaファイルから出ています。
エラー多すぎてどれを見ていただいたら良いのかが分からなかった状況です。
![37F406EE-A19E-4AD9-B2AE-10331BB78098](https://user-images.githubusercontent.com/91002836/211183697-afcec898-d27c-420d-9d02-00e9da883a17.jpeg)

**Comment by yoko-Developer** [comment]
>作業中のブランチでエラー解消したけど、
コンフリクトが気にるのでpushはしていないということですね？
その作業中にhtmlファイルが消えたという意味でしょうか？

その通りです。
【現在の状況】は、一緒に操作していただいたことを記載しています。
操作したときに混乱していて、そのまま開発を継続すれば良かったものの余計なことをしてしまいました。
