### ISSUE TITLE
SpringBootの実行方法

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#32]
エラーが35個表示されてしまったファイルは一旦放置し、cloneしました。
ひとつ前のバージョンになっていると思いますが、SpringBootが実行できません。
`MotocatalogApplication.java`ファイルを実行すると思うのですが、うまくいきません。

`MotocatalogApplication.java`を右クリックすると`Run java`と`Debug java`が表示されます。
![C8A5FED6-3835-43A7-836E-DBDED4A50B7E](https://user-images.githubusercontent.com/91002836/210062730-d710de21-c224-4ed5-a773-ad023b05a436.jpeg)

`Run java`を選択
この画面のまま表示が変わりません。
![E57568B5-9C3E-4BAD-B8D9-DB25C7F45B87](https://user-images.githubusercontent.com/91002836/210062936-04b28c53-cc2e-421e-9563-e979d003de5f.jpeg)

`Debug java`を選択
この画面のまま変わりません。
![F01EDDF7-6B9C-4D95-8E62-F26B1CF33175](https://user-images.githubusercontent.com/91002836/210063010-a33be805-4f6e-48d9-9045-a2cd222cb40e.jpeg)

「Run」「Debug」どちらを選択しても
MotocatalogApplication.javaがクラスパスにない場合、ランタイムがクラスが見つからないというエラーを投げることがある。
「motocatalog/motocatalog/src/main/java/jp/co/planaria/sample/motocatalog」をJavaのソースパスに追加したい。
と表示されるので「Add to Source Path」を選択すると
build.gradleに書くようにといった内容が表示されます。
![6DECB1C6-51FD-4E9E-913C-59971526B1C8_1_201_a](https://user-images.githubusercontent.com/91002836/210067129-b72e1868-adcc-401c-be4a-dd04b76c3f04.jpeg)

![8BFAC0F0-3D84-4DC3
![6DECB1C6-51FD-4E9E-913C-59971526B1C8_1_201_a](https://user-images.githubusercontent.com/91002836/210067021-5b7c51b5-c0dc-41ed-bfbb-484049f56acd.jpeg)
-869A-472202DE1681](https://user-images.githubusercontent.com/91002836/210066976-efefb4fb-39f4-475b-90c3-a90b16b661b5.jpeg)

build.gradle
```
plugins {
	id 'org.springframework.boot' version '2.7.1'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'war'
}

group = 'jp.co.planaria.sample'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation:2.7.4'
	implementation 'org.springframework.boot:spring-boot-starter-aop:2.7.4'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'mysql:mysql-connector-java'
	annotationProcessor 'org.projectlombok:lombok'
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

どうしたら実行できるでしょうか。
よろしくお願いいたします。

**Comment by yoko-Developer** [comment]
ターミナルのエラー表示
```
cd /Users/yoko/Documents/motocatalog ; /usr/bin/env /Library/Java/JavaVirtualMac
hines/amazon-corretto-18.jdk/Contents/Home/bin/java @/var/folders/c0/r2m2m7vx287_d0n3glfnkjpw0000gn/T/cp_9mi5h8k
5vq3w6ju10wq3vofqt.argfile MotocatalogApplication 
エラー: メイン・クラスMotocatalogApplicationを検出およびロードできませんでした
原因: java.lang.ClassNotFoundException: MotocatalogApplication
```

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
プロジェクト配下のbinの中にコンパイルされたクラスファイルは存在しますか？
![image](https://user-images.githubusercontent.com/22320079/210208471-7e9c639a-85ea-415c-9f14-d3c8449d59ae.png)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
また、「問題」タブを確認してみてください。
もしかしてコンパイルエラーが残っていませんか？

**Comment by yoko-Developer** [comment]
>プロジェクト配下のbinの中にコンパイルされたクラスファイルは存在しますか？
存在しているようですが、開けません。
これは正常なのでしょうか？
問題タブも表示してみましたが、コンパイルエラーはないようです。
というより問題がなぜか2個に減ってて、実行もできました。
結果往来ではありますが、全く納得できないです。。
![64509F92-AB9C-4FEE-A2DF-62E3FA522543](https://user-images.githubusercontent.com/91002836/210561106-e4471694-6eca-4c4c-918c-c476eae22c84.jpeg)

**Comment by yoko-Developer** [comment]
とりあえず、このまま開発を続けようと思っています。
現在の状態（クローンした状態）がどのバージョンになっているのか分かりません。
GIthubを確認すると、#29「見てください！」まで表示されているということは、プッシュしたところまで保存していると考えられると思うのですが、#29ブランチにチェックアウトして開発を続行しても大丈夫でしょうか。
![86D57F6D-F4BE-4EB7-9139-B3CB1F5C2BA9](https://user-images.githubusercontent.com/91002836/210562876-3f4148d7-fce6-41dd-ab8c-0537735539f6.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
現時点エラーもないのであれば、
クローンしなおして開発を継続するのはありだと思います。

**Comment by yoko-Developer** [comment]
ありがとうございます。
続けてやってみたいと思います。
