### ISSUE TITLE
git pushエラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#33]
#16 でgithubに保存しようとしたらエラーが表示されました。

![8C05608E-25A8-4724-B7FD-9B8007CE6C1D_1_201_a](https://user-images.githubusercontent.com/91002836/211197126-35c08a44-0d8a-4d9d-917b-212d15bf2f0d.jpeg)

リポジトリがないと怒られているようですが、リポジトリとブランチはあると思っています。
「正しいアクセス権を持っていることと、リポジトリが存在することを確認してください」
![9AC3F5E6-99A6-4D2F-8040-168D8D65A768_1_201_a](https://user-images.githubusercontent.com/91002836/211197130-18d6a7b1-49e8-4650-bbc3-815ef4f1e37c.jpeg)

`git push origin feature/#29_date_lock_and_rollback`
エラー
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
cloneしたからできなくなっているのでしょうか。
どうしたら良いのか教えていただけますか。

**Comment by yoko-Developer** [comment]
`git status`してみたところ未追跡ファイルが大量に表示されました。
以前にもこの状態になったことがあり、何度か最初から作り直した経験があります。

やったこと
・#15までのファイル達をclone
・2度ほどcommitして#16が完成したため`add. ` `commit` `push`

現状
・上の投稿通り、エラー表示されている

確認したこと
・リモートブランチ
→ないと怒られていたが、`feature/#29_date_lock_and_rollback`が存在する（2枚目画像）
・`git status`
→Githubに保存しているリポジトリやファイルが未追跡
→Githubのリポジトリは正常に存在している
・`git remote -v`
→`origin  git@github.com:yochan0120/MyTodo.git (fetch)`
`origin  git@github.com:yochan0120/MyTodo.git (push)`

MyTodo？が表示されるのもおかしい気がしますが、MyTodoというリポジトリはありません。
SourceTreeを確認したら、コミットに「461」と記載されています。
現在の状態がどうなっているのかすら、理解できません。
どうしたら宜しいでしょうか。
よろしくお願いいたします。

![A30AA12D-8E15-4AC8-AD86-E185C6FFC519_1_201_a](https://user-images.githubusercontent.com/91002836/211259998-0cf0deb5-26b4-40b8-a0ad-a70b0e2710e8.jpeg)
![2B3EE048-8FA6-4F81-ACF3-EFCEC4514A99_1_201_a](https://user-images.githubusercontent.com/91002836/211262032-6288bde1-352a-43b6-8aa5-787b1ac85849.jpeg)
![2D74C2D5-827E-42B9-9818-43926F40F4FE_1_201_a](https://user-images.githubusercontent.com/91002836/211268525-485c2850-62dd-43c2-b8cb-15d0ccafae76.jpeg)

**Comment by yoko-Developer** [comment]
もう一度やり直しました。
手順が間違えていないか見ていただけますか。
・git clone
ファインダにmotocatalogフォルダを新規作成
ターミナルでカレントディレクトリをmotocatalogに移動
Githubのmotocatalogリポジトリ→Code→SSHをコピー
git clone [SSHのURL]
```
git clone yoko-newDeveloper/motocatalog.git
```

ブランチfeature/#29_date_lock_and_rollbackで開発
`git branch` ブランチ確認
`git status` 差分確認
motocatalogと無関係のファイルが大量表示される
![4C6DC6C4-D258-4062-A627-32D983F8D115_1_201_a](https://user-images.githubusercontent.com/91002836/211307157-73a3bcc3-9b4f-486f-b351-e89d7f540d93.jpeg)

git log
意図しない過去のファイル？が表示されています。
```
commit 32b5f56aa704228a6bfdecad74e8bfae1d7a32e9 (origin/main, origin/HEAD, main)
Author: Yoko Morioka <91002836+yochan0120@users.noreply.github.com>
Date:   Tue May 10 12:37:44 2022 +0900
```
![4F958799-A242-4AA7-A58A-D48FAB2048EB_1_201_a](https://user-images.githubusercontent.com/91002836/211307412-1b619ed2-0c95-4f77-993f-c237d65f4ae5.jpeg)

**Comment by yoko-Developer** [comment]
今回追加したいのは下記です。
pushしていないcommitが2つ
`git commit -m "楽観的排他制御した"`
`git commit -m "ロールバックできるようにした"`
最後に作成した
`git commit -m "エラーメッセージを整理した"`

cloneしただけで、ローカルで開発をしただけの状態なのに、pushしていないコミット履歴が表示されているのは何故ですか。
pushしていないのに表示されるのでしょうか。
益々分かりません・・・。
前回と同様にこのまま`add`や`push`しても同じエラー表示されると思います。

`git diff`も実行しました。
`git diff staged`では何も表示しませんでした。
![8ABF2D3F-2D39-4EA8-B86E-98F86D9A9633_1_201_a](https://user-images.githubusercontent.com/91002836/211310351-0848d19d-2636-4b2f-9d78-1fb85406efc0.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
今回のはパッと見は難しい内容でしたね。

プロジェクトの一階層上のフォルダに `.git` があって、
それがローカルリポジトリとして判断された現象でしたね。

日頃からフォルダを整理しておくとよさそうですね。
私の勉強にもなりました。
ありがとうございました。

**Comment by yoko-Developer** [comment]
本当ありがとうございました。
ファインダーのフォルダが影響しているとは・・・同じフォルダ以外は見ていませんでした。
もう少し整理して管理したいと思います。
ありがとうございました。
