### ISSUE TITLE
git commitについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#36]
git commitで変更したところまでローカルに保存しておけるという認識ですが、cloneするとリモートmainの内容となるためローカルでcommitしていた内容が破棄されてしまうと思います。
commitしたところまで戻るにはどうしたら良いでしょうか。
Sourcetreeだと自分の作業ブランチ（commitしたファイル）が表示されますが、コマンドではどうしたら良いでしょう。
[検索結果](https://qiita.com/Yorinton/items/e0e969d961b17a359e19)
見つけましたが、よく分からないので教えていただけますか。
``
$ git log //戻す対象のハッシュ値を調べる
commit ************************
``

$ git reset --hard ハッシュ値
よろしくお願いいたします。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

状況がちょっと見えないですね。

1. ローカルでリポジトリを作成
2. コミットして変更内容を残した
3. リモートリポジトリをあとから作成
4. クローンでリモートリポジトリをローカルリモートリポジトリに取得した（ローカルが壊れた）

その状態だとローカルリポジトリが存在しているので
リモートリポジトリをクローンするときにエラーが出そうな気もしますが。
クローンできたということは階層のことなるフォルダに異なるリポジトリが存在しているようにも思いますね。
しかし、Sourcetreeだとコミットした状態が見えるとのことですしね。

私の仮説通りの状況であれば、
片方のリポジトリの.gitフォルダを削除することで解決できるかもです。

**Comment by yoko-Developer** [comment]
説明が下手ですみません。
先生の動画でもpushしないで、ここまでをcommitしておきましょうというシーンが複数回あります。
cloneすると（ローカルで）commitしたところには戻れないので、commit後にミスした場合にcommitまで戻るコマンドを知りたいと思います。

不具合というわけではないと思うのですが、単純に以前のcommitまで戻る方法が分かるといいなと思っています。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

とりあえず戻りたいだけなのであれば`git checkout コミットハッシュ`とかどうですか？

https://qiita.com/yt_andante_11/items/866e45d771b28cf05bf2

もしくは`git reset`を使うのは？
あとは、sourcetreeなどで特定のコミットを指定してブランチを作るのもいいですね。

**Comment by yoko-Developer** [comment]
`git lig`でコミットハッシュを探して、checkoutするんですね！
色々やり方はあるってことで、とても勉強になります。
ありがとうございます😀

**Comment by HyunwookPark** [comment]
私は最後に提案したブランチつくる方法をよく使っています。

**Comment by yoko-Developer** [comment]
ありがとうございます。
今度エラーになったときに新しいブランチ作るの挑戦してみます！
