### ISSUE TITLE
コードレビューについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#37]
スクールでも実務でも、実装したらプルリクエストをすると思います。
一生懸命調べて何とか動かせても、全否定されることがあります。
この書き方よりこっちがいいとか、パーツ的に直すくらいなら当然だと思いますが、最初から実装し直すように指示されると物凄く悲しくなります。
素人からすると動けばいいじゃん！とか最初からこれ使ってって言ってよ！と思ってしまうのですが、先生はレビューするときにどんなことを重んじていらっしゃいますか？
暗黙のルールとかはあるしケースバイケースなのは分かります。
先生の基準を教えていただけますか。
抽象的で変な質問ですみません。よろしくお願いいたします。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

コードレビューについては私も一度整理したいと思っています。
いくつか挙げてみますね。

- 同じコードが重複していないこと（共通処理の可能性はないか）
- 処理が複雑になりすぎていないか
    - シンプルに同じことをする方法があるか
    - 複雑さは不具合の元
- 適宜コメントを書いているか
- クラス名・メソッド名・変数名が適切か
- 他の実装方法と統一感が取れているか
- ネストが深すぎないか
- 処理の負荷が上がることをしていないか
    - ループ内でSQL実行
    - ファイルの一括読み込み
- 構文の限界を超えることがないか
    - SQLのIN句の上限数
    - メソッド数や行数の上限
- コーティング規約に沿っているか

などかなり多くありますね。

まとめると2点でしょうか。

- **他社がメンテナンスしやすく作っているか**
- **不具合の可能性はないか**

動けばいいじゃんと思う気持ちはわかりますが
そう思って作っていてはいつまで経っても技術が改善されることはありませんね。
あとでメンテナンスする人はもちろんのこと自分がメンテナンスするときも苦労します。

事前に利用してほしいパーツ（部品など）を開示するのは
プロジェクトとしてやっておくべきです。
ただ、予算や忙しさの関係でできていない場合も多いですね。
部品一覧とサンプルコードを準備するのが望ましいのは間違いありませんが
すべてのパターンについてサンプルを書くわけにもいかないし
部品一覧もプロジェクト内で作ったものを一覧にするぐらいが限界でしょう。

**Comment by yoko-Developer** [comment]
丁寧に回答してくださりありがとうございます。
動けばいいじゃんというのは乱暴な言い方ですが、ルールを提示されていないのでどこに気をつければ最初から作り直すことが無くなるかなと思っています。
経験を積めば少しずつ分かって来るかもしれませんが、一流の先生ならどういう基準かなと考えていました。
>不具合の可能性はないか

これは具体的にどんなことが考えられますか。
動いているけど、条件が変わると動かなくなるとかということでしょうか。

全部難しいですね。。
諦めませんけど笑。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> これは具体的にどんなことが考えられますか。

これはコードによるのは何とも例を挙げづらいですね。

おっしゃるとおり、条件やパラメータによって動かなくなることのほかにも色々考えられそうですね。

- そもそも仕様と違うコードになっている
- 必要な処理が漏れている
    - 一覧検索の順序指定など
- nullの扱いの考慮が足りない
- ループの条件が間違っている
    - `<`と`<=`の間違いとか日常茶飯事です
- エラーメッセージなどの文言ミス

挙げればキリがないですね。

正直、レビューするのはかなり難易度が高いし面倒な作業です。
人がミスしそうなところを予想しながら実際の仕様を把握して
自分ならどう作るかを想像しながら
相手が書いている難解なコードを解釈しているわけですからね。

当然、指摘もれもあって、
思い出して五月雨式に伝えると「一回で言ってください」とか言われ
細かいところまで指摘すると「それはあなたの趣味ですよね？」とか言われ
精神的にも辛い作業です。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

レビューされる側ももちろん大変ですが、
レビューする側も最も気が進まない作業のひとつをやっていると思って
優しい心で理解してあげてください。

互いの負担が減りそうな提案があれば進んで提案してあげてください。^^

**Comment by yoko-Developer** [comment]
私の場合は全く知識もスキルもないので、言われた通りに修正に挑戦するだけなんですけど笑。
あなたの好みでしょ？って思ってしまうこともあります😂
スクールでも業務でもオンラインで、顔を合わすことがないのでバレてないとは信じたいですが。。
大変だなーと思います。
相手に分かるように回答することも難しいですしね。
先生も優しい心でレビューしてくださいね😇

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
心を鬼にしてビシバシいきます（笑）

**Comment by yoko-Developer** [comment]
そんな😂
いつも通り優しくお願いします！
