### ISSUE TITLE
vscode

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#38]
motocatalogの動画でもvscodeを使用されているので、vscode開発に挑戦しています。
動画では停止マークを押すと停止されますが、このアイコン達を出す方法はあるのでしょうか。
業務（Windows10 vs.code）ではこれらのアイコンは表示せず、「ctrl ＋ c」で停止します。
motocatalog開発（mac）では「⌘ + c」で停止しません。
OSは関係ないと思いますが、表示方法や設定などがあれば教えていただけますか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

昨日一緒にやったように`launch.json`を作成すると起動や停止のボタン使えるよになります。

![image](https://user-images.githubusercontent.com/22320079/216805850-928c26e4-3bc8-4e67-b5aa-5fff0e3b4fc6.png)

**Comment by yoko-Developer** [comment]
ありがとうございます！
明日Windowsでやってみます。
手軽に実行や停止ができたら嬉しいと思っています。

**Comment by yoko-Developer** [comment]
実践してみました。
launch.jsonのプルダウンでどれを選べばよいでしょうか。
選択肢：Launch Chrome against localhost/Node.js/AddConfiguration
どれを選択してもうまく行きません。
▷アイコンは表示されています。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
vue.jsの起動の方はちょっと難しいようです。
できなくはないけど、
実戦では`yarn serve`でvueアプリを起動しておいて
デバッグ機能を使うためにデバッグ用のChromeを起動するという方法を使うようです。

私もこの辺りは詳しくないですけどね。

**Comment by HyunwookPark** [comment]
先日はvue.jsもたぶんJavaと同じ様にできると思うよーって言ってしまいましたが訂正させてください。🙏

**Comment by yoko-Developer** [comment]
ありがとうございます！
vue.jsは少し難しいんですね。
とりあえず従来のやり方で進めたいと思います。
楽できる方法あったら、また教えてください。
