### ISSUE TITLE
DDD

### ISSUE THREAD

**Issue by otowmoyarng** [HyunwookPark/question-box#4]
DDDで開発するためにドメインモデルを作る練習をしたいのですが、
販売とか労務とか、そもそもドメイン知識も少ないので
どんなテーマで練習したらいいか検討つかないです。

先生は何で習得されましたか？教えてください。

**Comment by HyunwookPark** [comment]
正直、私もDDDはよくわからんと感じています。
ですので、私の返事としては「私もよくわかりません！」です。（笑）
勉強不足ですみません🙇

オブジェクト指向で概念モデルの抽出から設計すると自然にドメインぽくなるのでは？と思ったりします。
それをあえてドメインと呼ばせる意味は？とかも思ったり。
いや、私の理解が足りてないだけかもしれませんけどね。

DDDは度々書籍やインターネットの記事などで理解を試みますが、
その度に「結局なんなん？」と挫折しています。（汗）

周りの優秀なエンジニアも難解と感じているようなので、
あえて使わなくてもいいかなと思ったりもします。

システム開発は研究ではないので後任者がメンテナンスしづらいぐらいなら
多少不細工で非効率的な部分があるとしても明確でシンプルな方式を選択すると思います。

**Comment by HyunwookPark** [comment]
リポジトリとか登場するのもDDDでしたっけね？？
なんだか多くのシステムが中途半端なDDDかじりの感じになっているような気もしますね。

よくわからんのなら無理して使わんでもと思うのですが、これは言い訳ですかね😅

**Comment by otowmoyarng** [comment]
> DDDについて

正しく設計してきれいなコードで実装したら、結果てきによいドメインモデルができる
それを実現できるようなエンジニアになれればと思いますので、
今後もご指導ご鞭撻のほど、よろしくお願いします。

> リポジトリについて

リポジトリはDAO系のプログラムをビジネスロジックから切り離したファクトリーパターンです。
ビジネスロジックから切り離なすことで、どのDBにも接続して使用することができます。
MyBatisのDAOインターフェスは代表的なリポジトリパターンになります。

**Comment by HyunwookPark** [comment]
> 今後もご指導ご鞭撻のほど、よろしくお願いします。

こちらこそよろしくお願いします。
私はまだまだその域に達していないのでこれからも頑張っていきます。

> MyBatisのDAOインターフェスは代表的なリポジトリパターンになります。

なるほど。そのような考え方もあるんですね。

私はリポジトリとDAOは異なるものと考えています。
リポジトリはデータを保管したり取り出すためのもので、
MyBatisを使ったDAOはSQLを楽に実行できるものという感じに捉えています。

DAOもデータアクセスオブジェクトなので
データを保管し取り出すのは同じというふうにも捉えられますが、
リポジトリの方がドメイン内のデータ構造を扱う
業務的な意味合いの強い思想かなと捉えています。

DAOのメソッドなら
`selectByPk()`とか`insert()`とか`update`という感じで、
リポジトリのメソッドなら
`findByItemId()`とか`store()`とか`save()`という感じ。

屁理屈にも思えるかもしれないし、
私の理解が間違っているのかもしれませんけどね。


ちなみにこの考え方があって、
MyBatisのMapperインターフェースを `~Repository` と名付けるのは反対しています。
Mapperは `~Mapper` と名付けています。

**Comment by otowmoyarng** [comment]
Mapperはインテグレーション層へのDAOで、
リポジトリはモデルに近いドメインオブジェクトという解釈なんですね。

私の解釈が間違っておりました。
バックエンドでの処理フローを考えると依存の向きが統一できますね。
Controler＜Service(Usecase)＜Repository＜Mapper

しゃちょー、さすがっす。
ありがとうございます！勉強になりました。

**Comment by HyunwookPark** [comment]
いえいえ、どちらが正しいというよりは「私は」そう考えるというだけですので、
ひとつの考え方と思って頂ければと思います。

ちなみに、
RepositoryとMapperを合わせて使うこともあまりないですようですので
「＜Repository＜Mapper」この関係性は発生しないのかもしれません。

JPA使うなら
Controler＜Service＜Repository
MyBatis使うなら
Controler＜Service＜Mapper
ぐらいの乗りで考えています（笑）
