### ISSUE TITLE
使われていないimport文について

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#40]
黄色い〜が付いていて使われていないとのことなので、下記操作をしたらずっとループされてしまいます。
・⌥ + ⇧ + Oで不要なimportを削除
<img width="1512" alt="1436D951-A278-47EA-9040-48F45BC828C7" src="https://user-images.githubusercontent.com/91002836/216800595-eff9b594-4e8c-423f-bbc6-9afccf0d9fba.png">

・øが自動的に記述されて赤い〜が表示
![97E1337F-3768-4B51-A05D-C33DE99E62AD_1_201_a](https://user-images.githubusercontent.com/91002836/216801056-b4039625-244e-44d1-bfa0-6695f69f8752.jpeg)

・手動でøを削除→違うimport文に黄色い〜が表示
<img width="1512" alt="3A8C25D1-96A7-4115-9C4E-56EAF9B61401" src="https://user-images.githubusercontent.com/91002836/216800631-7ace6c46-ac56-4224-9212-cdf966cb606b.png">

・また他の場所にøが自動的に記述→赤い〜エラーが表示
![69027A1F-333C-479F-9D31-C8B17B1AF6FF_1_201_a](https://user-images.githubusercontent.com/91002836/216801063-9ec8fb41-fcf8-43c2-9743-cab3c17a03bf.jpeg)

・下に戻して、import文を手動削除
→下記２箇所に赤い〜
　`List<Brand> brands = new ArrayList<>();`の`Brand`
　`brands = service.getBrands();`の`brands`

使われていないimport文を削除するには、どうしたら宜しいでしょうか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

謎現象ですね。
VSCodeの再起動かJAVA PROJECTの再ビルドを試してみてはどうですか？

**Comment by yoko-Developer** [comment]
多分ハングってたことが原因のようです。
vscode再起動で解決しました！
