### ISSUE TITLE
branchについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#41]
無事に#17が終わりました。
【現在の状況】
・ブランチ：feature/#32_insert_deleteで開発
・margeまで終了

【確認事項】
・git branch　カレントブランチを確認（1枚目画像添付）
・Git glaph（2枚目画像添付）

【疑問点】
・commitやpushをする前にカレントブランチを確認しているのに、mainブランチで開発したように見えます。
・画像にテキストで記載した内容が自分の認識です。（3枚目画像添付）

操作が違う
認識が違う
どちらでしょうか。

![019A7FA7-7E16-4141-8CC5-A27E7BE767F3_1_201_a](https://user-images.githubusercontent.com/91002836/216803301-a3e9b182-7f79-4dd2-94e4-f36e9835563d.jpeg)

<img width="1512" alt="1D44EF98-C267-4F08-AA38-C442E33D75D6" src="https://user-images.githubusercontent.com/91002836/216803330-2f3ec572-0620-4949-929b-f24b76abbe59.png">

![0EBCA20B-7173-42C5-890F-84A8841EDE8A_1_201_a](https://user-images.githubusercontent.com/91002836/216803884-5936bc84-e7a4-4d03-856c-590945d3c34f.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> 認識が違う

のほうですね。
つまり、現状で大丈夫です。

![image](https://user-images.githubusercontent.com/22320079/216806052-6a947aa7-c2eb-4862-9534-6ff152cf7ef6.png)

`feature/#32_insert_delete`ブランチで作業できていますよ。
`main`ブランチと色が同じなのでそう見えますが、`main`ブランチは更新されていないです。

**Comment by yoko-Developer** [comment]
一番上のブランチ名が
`git checkout -b feature/#32_insert_delete`
だから問題ないということですね。
ありがとうございます。

pushしてmainブランチからpullしたのですが、mainは更新されてないのでしょうか。
現在カレントがmainになっていますが、mainから新しいブランチを切って問題ないでしょうか。

**Comment by yoko-Developer** [comment]
もう一度確認させてください。

【現在の状況】
・feature/#32_insert_deleteはissueを紐付けしてpr、merge済み。
・mainから新しく次のブランチfeature/#34_update_validationを切った。

【疑問点】
・Git glaphを確認すると、mergeされていないように見える
・issueが残っている

<img width="1512" alt="D1EEACB8-7CB7-4950-8187-F30F6345999D" src="https://user-images.githubusercontent.com/91002836/216808101-e4f5c0c2-0557-4e96-90c4-0a55d0990fd3.png">

![E4B561D3-CED9-43F3-BE59-4527B37393C7_1_201_a](https://user-images.githubusercontent.com/91002836/216808156-3d9b555b-0a03-4532-9a61-6ddc6712e078.jpeg)

【確認事項】
・Githubの登録と削除を開く→Deveopmentに紐付けできるissueは残っていない
・feature/#34_update_validationを実行すると、「削除」ボタンがない
・feature/#34_update_validationを実行すると、「新しいバイク登録」ボタンを押しても無反応
・実装済みでgit checkout -b feature/#32_insert_deleteに切り替えると「削除」が表示、「新しいバイク登録」が反応する
・git diff feature/#32_insert_delete origin/main→複数表示
・カレント：feature/#32_insert_deleteで、git push origin main→Everything up-to-dateと表示
・SourceTree：カレントブランチfeature/#29_date_lock_and_rollbackのままチェックアウトできない
・コマンドではブランチ切り替え可能
・SourceTreeとGit glaphの表示が違う（ように見える）

【質問事項】
・mergeしたらGithubの一覧（2枚目画像）から表示がなくなると思いますが残っているのは操作の問題でしょうか。
・mergeしたらGit glaphのmain（1回目画像/一番左の青い線）にピンクがくっつくと思っていますが、認識が違うでしょうか。
・mergeできていないと思いますが、どうすれば良いでしょうか。


<img width="1512" alt="44EEFD30-7A69-451A-B797-3E7F413CCC03" src="https://user-images.githubusercontent.com/91002836/216815169-eebfc7a6-fb54-45dc-af56-caa5881a3012.png">

**Comment by yoko-Developer** [comment]
【試したこと】
①pull requests
②New pull request
③SourceTreeのブランチをfeature/#32_insert_deleteにチェックアウト

【結果】
①②Create pull requestがグレーアウトしている
③エラー表示
```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree checkout -b feature/#32_insert_delete --track origin/feature/#32_insert_delete 
error: Your local changes to the following files would be overwritten by checkout:
	src/main/java/jp/co/planaria/sample/motocatalog/controllers/MotosController.java
	src/main/java/jp/co/planaria/sample/motocatalog/mappers/MotorcycleMapper.java
	src/main/java/jp/co/planaria/sample/motocatalog/services/MotosService.java
	src/main/resources/messages_ja.properties
	src/main/resources/templates/moto.html
Please commit your changes or stash them before you switch branches.
Aborting
Completed with errors, see above
```

【思いついたこと】
・pull requestがあるのは無視して、登録と削除のissueをcloseで解決？
→でもmergeされるのか不明→多分されない
・feature/#29_date_lock_and_rollbackをカレントにしてgit stash
→関係ないかも

<img width="1512" alt="93CD59E4-EA74-46D9-AECF-674B81AD0B5E" src="https://user-images.githubusercontent.com/91002836/216809778-c2f7fb85-3193-49f0-9a78-0d25d7c6ff8b.png">
<img width="1512" alt="1ED864BA-7952-4EAE-8A39-39B5F94D8533" src="https://user-images.githubusercontent.com/91002836/216809782-de325e1e-a529-4beb-a639-57475a76cec4.png">

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
質問を箇条書きにしてくれていますが、ちょっとやりすぎな感じですね。
なにを言いたいのかわからなくなっちゃいました。^^;

文章が長すぎる➡箇条書きにするという単純な感じではなくて
「相手はこの情報を渡す必要がありそう」「必要な情報を書きすぎて長くなって読みづらそう」
という感覚なんですが、バランスは難しいですよね・・・^^;

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

`feature/#32_insert_delete`が`main`ブランチにマージされていない状態で
次のブランチを作成したために起きている現象と思われますね。

**Comment by yoko-Developer** [comment]
色々試しすぎて、ごちゃごちゃになってしまいました😂
シンプルだと情報が少ない
多すぎると何が言いたいのか不明
難しいです・・・。
>feature/#32_insert_deleteがmainブランチにマージされていない状態で
>次のブランチを作成したために起きている現象と思われますね。

git diff feature/#32_insert_delete origin/mainでファイルが複数表示されるので私もそう思いますが、git pushしても`Everything up-to-date`と表示されてしまいます。SourceTreeでpushしてみようと考えましたが、feature/#29_date_lock_and_rollbackからcheckoutできません（なのでpushできません）
どうしたら良いでしょうか。
というのが、現時点での質問です😓

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
んー、ちょっと状況が見えないですね。

> git diff feature/#32_insert_delete origin/mainでファイルが複数表示されるので私もそう思いますが、git pushしてもEverything up-to-dateと表示されてしまいます。

これはなにを証明したいのでしょうかね。

現状のgit graphを見せてください。

**Comment by yoko-Developer** [comment]
すみません。
とりあえず画像添付します。
>これはなにを証明したいのでしょうかね。

`git status`を実行
実行結果↓
```
On branch feature/#32_insert_delete
Your branch is up to date with 'origin/feature/#32_insert_delete'.
nothing to commit, working tree clean
```
コミットするものはないそうなので、`git diff feature/#32_insert_delete origin/main`
feature/#32_insert_deleteとmainブランチの差分を確認しようと思いました。


https://qiita.com/kahorno/items/323c58d0dfaa3212f442
これ実行しましたが、うまくいきませんでした。
よろしくお願いします。
<img width="1512" alt="4BF07ABF-B2BD-406C-8FC8-5034F1F1E94F" src="https://user-images.githubusercontent.com/91002836/216816454-1b0af752-6e4a-4df1-8520-8e7e906b9bf3.png">

**Comment by yoko-Developer** [comment]
元々feature/#32_insert_deleteで実装した時のコマンドを添付します。
②は動画にありませんが、自分でコミットしたものです。
どこを間違えて今の状態になったのか分かりません。
見ていただけますか。

①$ git branch
②$ git add.
　$ git commit -m"削除処理を実装"
③$ git branch
④$ git add .
　$ git commit -m"削除機能できた"
⑤$ git push
⑥$ git push --set-upstream origin feature/#32_insert_delete

リモート：Githubでの操作
![F0920080-2C6B-48A6-9A14-32C3C8797B7F_1_201_a](https://user-images.githubusercontent.com/91002836/216818465-4e81e5ec-a233-42d9-b716-e5f644e4798c.jpeg)

git reflog で操作履歴を見ると#32は存在していますが、、、
<img width="1512" alt="FA6DE9EA-2393-4FD3-BFD1-4FECEA8FA47C" src="https://user-images.githubusercontent.com/91002836/217113212-3fa3de79-c70b-4d7e-b5d5-94b768afa6da.png">

**Comment by yoko-Developer** [comment]
・ebf4e8d　【現在のHEAD】
feature/#32_insert_deleteからmainへチェックアウト
・b1cb8e5　【1つ前のHEAD】
mainからfeature/#32_insert_deleteへチェックアウト
・ebf4e8d　【2つ前のHEAD】
feature/#32_insert_deleteからmainへチェックアウト
・b1cb8e5　【3つ前のHEAD】
feature/#34_update_validationからfeature/#32_insert_deleteへチェックアウト
・2cbd58c　【4つ前のHEAD】
mainからeature/#34_update_validationへチェックアウト
・ebf4e8d　【5つ前のHEAD】
 feature/#32_insert_deleteからmainへチェックアウト
・b1cb8e5　【6つ前のHEAD】
feature/#32_insert_deleteからfeature/#32_insert_deleteへチェックアウト
・b1cb8e5　【7つ前のHEAD】
feature/#34_update_validationからfeature/#32_insert_deleteへチェックアウト
・2cbd58c　【8つ前のHEAD】
SearchFormクラスのパッケージ移動
・ebf4e8d　【9つ前のHEAD】
mainからfeature/#34_update_validationへチェックアウト
・ebf4e8d　【10個前のHEAD】
feature/#32_insert_deleteからmainへチェックアウト
・b1cb8e5　【11個前のHEAD】
削除機能できた
・39cfe12 【12個前のHEAD】
削除処理を実装
・2ca7e32　【13個前のHEAD】
登録機能できた
・1f018f6　【14個前のHEAD】
排他エラー発生時ドロップダウンが表示されるようにした
・ebf4e8d　【15個前のHEAD】
mainからfeature/#32_insert_deleteへチェックアウト
・ebf4e8d　【16個前のHEAD】
github.com:yoko-newDeveloper/motocatalog.gitをクローン

git logを確認すると#32はありませんでした
どこで間違えたのか分からず、どうしたらいいのか相変わらず分かりません・・。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

> ・ebf4e8d　【現在のHEAD】
> feature/#32_insert_deleteからmainへチェックアウト
> ・b1cb8e5　【1つ前のHEAD】
> mainからfeature/#32_insert_deleteへチェックアウト
> ・ebf4e8d　【2つ前のHEAD】

これはgit reflogの説明ですね？ここから特に伝えたい部分はありますか？（情報と一緒になにを読み取ってほしいか伝えるとよさそうです）
操作上 #32にcheck outできているのでブランチは存在すると判断してもいいでしょう。

そもそもなにを確認したいのかがわからなくなってきました。^^;
「#32ブランチが存在するかどうか」ではなくて
「#32ブランチも#34ブランチもmainから派生して作業してしまった」
ということですね。

#32のブランチがmainにマージされたかは判断できませんが
#34のブランチを作成するときにmainブランチに切り替えていなかったのが原因と思われます。

**Comment by yoko-Developer** [comment]
>これはgit reflogの説明ですね？

はい。
操作が間違えてないか、どこで間違えたのかが分からなかったのでgit reflogをやってみました。
困っているのはmainブランチで#32の変更が反映されていないことです。
ブランチが存在していることは分かるのですが、実行すると#32ブランチに切り替えたら表示される内容と、mainに切り替えた時に表示される内容が違うんです😭
この状態、どこを間違えたのか？
どうしたらmainブランチに#32の変更が反映されるのか？
を知りたいと思っています🙇‍♀️

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
もっとも単純な方法はプルリクエストを再度作ってマージしてみることです。
他には、ローカルのmasterブランチに#32ブランチをマージする方法もあります。

**Comment by yoko-Developer** [comment]
簡単な方がいいので、もう一度プルリク作る方法でやってみようと思います。
後日になりますが挑戦するので、またうまく行かなかったら相談させてください🙏

**Comment by yoko-Developer** [comment]
早速プルリク作ってマージしてみました。
1枚目画像を確認するとマージOK、mainもプルOKだと思います。
よろしくお願いします。。

【困っていること】
・#34 にチェックアウトできない
・エラーメッセージ：`error: pathspec '#34_update_validation' did not match any file(s) known to git`

【やりたいこと】
#34にチェックアウトできない

【やったこと】
・#32でプルリクエストを作成し、mainにマージ

【試したこと】
・git fetch
![EBDFE8CD-4E29-4386-B07E-C19099E18683_1_201_a](https://user-images.githubusercontent.com/91002836/218633761-458c0e90-65d7-465e-92e7-fc53c9eaa7c8.jpeg)
<img width="1512" alt="A4A56BAA-3BDC-48F1-BD2F-E5AB7D29C07F" src="https://user-images.githubusercontent.com/91002836/218633783-5116cbda-57f3-412d-b037-057c86c7b57c.png">

**Comment by yoko-Developer** [comment]
mainブランチから新しいブランチ切って、#34の最初から実装するしかないでしょうか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

`error: pathspec '#34_update_validation' did not match any file(s) known to git` と書いてあるとおりのようにも思えますが
ブランチ名間違ってませんか？

**Comment by yoko-Developer** [comment]
ブランチ名変更したのに、前のブランチ名をコピーしたことが原因でした。
すみません。ありがとうございます。
