### ISSUE TITLE
cssプロパティの順番

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#42]
<style>の書き順についてです。
どんどん上書き（下段が適応）されるのは理解していますが、クラスを書く順番はどのようにするのが良いでしょうか。
（プロジェクトルールで決まっていない場合です）
アルファベット順かhtml順かなと思いますが、何となくhtmlで書いた順に書いています。
ルールやベストプラクティス、先生の考え方を教えていただけますか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
素晴らしい質問ですね。

ベストプラクティスは難しいですー。
プロのデザイナーさんでもCSSのつくりを見るとぐちゃぐちゃなことはよくあります。
もちろん私もぐちゃぐちゃになってることよくあります（笑）

それだけコードの整理は難しいということでしょうね。

CSSをひとつのファイルにすべて書くのかファイル分割するのかによっても
方針は異なってきそうです。

ちなみに私はアルファベット順にはしてないです。

大きくは「システム全体のCSS」と「画面個別のCSS」にファイルもしくは書く場所を分けています。

1. システム全体の方は影響が全体に渡るものほど上に書いています。
1. 画面個別のCSSの方は画面の部品の配置の上から順に書いています。
1. それぞれのCSSで同様のことをやっているものはできるだけ同じ個所に書くようにしています。

1～2と3は両方を満たすのは難しいので結果的に多少ぐちゃぐちゃになっちゃってますね。
3は異なる画面の要素で同様のことをやっているCSSをまとめようとするので
画面の配置の上からにならなくなってしまいますしね。矛盾・・・

など試行錯誤しています。
ひとつ大事だと思うのはCSSもしっかりコメントを書くことです。
プログラムのソースコード以上にCSSは作った人以外が読み解くのが難しいです。
どんな用途で作ったものなのか。なにをまとめたブロックなのか。などを記載するといいと思います。

ベストプラクティスではありませんが参考になれば幸いです。

**Comment by yoko-Developer** [comment]
素晴らしい質問と言っていただけて、物凄く元気出ました！！😆
ありがとうございます。
まだ勉強中なので、極力変な癖をつけたくなくて、色々聞いてしまってすみません。

なるほど〜、奥が深いのですね。
CSSファイルにまとめて書くか、ひとつのファイルにCSSも書くかとかも迷ってしまいます。
長いソースになった場合は分ける？と思っていますが、同じファイルの方が確認しやすいとか、そもそも長いソースは書けないということもあり、ひとつに纏めてしまうことが多いです。
処理の順番に書くというのが良さそうですか。
それも難易度高いですよね。
先生のやり方を参考にできるように、努力したいと思います。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
勉強レベルではそんなにCSSの内容も多くないでしょうし、ファイル1つでよさそうです。
実際の業務になれば自然と多くのファイルになると思いますよー。

**Comment by yoko-Developer** [comment]
そうですよね。
とりあえずひとつにして、順番をきちんと考えたいと思います。
