### ISSUE TITLE
ファインダーのフォルダ名変更

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#44]
フォルダについて質問お願いします。

【やりたいこと】
・git cloneしたい
・git cloneの準備として、motocatalogフォルダを「error-motocatalog」にリネームしたい

【やったこと】
・motocatalogフォルダのリネーム
・motocatalog→error-motocatalog
・リネーム後、vscodeの「エディタを閉じる」を押下

【現在の状況】
・やったことの３行程実施したところ、「motocatalog」という名前のフォルダが自動生成された
・自動生成されたフォルダを「what-motocatalog」にリネーム

【確認したこと】
・what-motocatalog：2枚目画像の通り保存されている
・error-motocatalog：プロジェクトすべてのファイルが保存されている

【疑問点】
・シンプルなリネーム操作のはずですが、正常な挙動でしょうか
→motocatalog→error-motocatalogにリネームすれば、motocatalogは生成されないと思っていました
・上記理解について、誤りがありますか？
・what-motocatalogは削除して問題ないでしょうか

<img width="1512" alt="6768D863-21E8-4C6E-B091-BD209C9A298C" src="https://user-images.githubusercontent.com/91002836/219922600-a31bb910-1663-4f4c-85bc-7b747dcbceed.png">

![C829B5F4-AE98-450D-831D-466D33C51368_1_201_a](https://user-images.githubusercontent.com/91002836/219922605-fe3f2b72-0738-4967-8316-6861d4fa6041.jpeg)

**Comment by yoko-Developer** [comment]
lsコマンドを実行するとapp logがあります。
これも正常でしょうか。

![5529DCC9-85BD-4382-99E3-9E6F129C3730_1_201_a](https://user-images.githubusercontent.com/91002836/219922859-4265d567-59ec-4b21-9176-a34bfb9eaec2.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

んー、VSCodeで開いているフォルダをfinderからフォルダ名変更したということですね？
VSCodeでルートとして開いているフォルダ名を変更したいのであれば
VSCodeを完全に閉じてからにしましょう。

VSCodeでmotocatalogフォルダをパス指定で開いているのに
フォルダが消えてしまうことになるので、
VSCodeは仕方なく再度フォルダを生成したものと思われます。

**Comment by yoko-Developer** [comment]
確かに、基本的な問題でした。
他の問題で気を取られていました。
ありがとうございます。
