### ISSUE TITLE
vscodeの実行方法

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#45]
先日も教えていただいた件で申し訳ありません。

【やったこと】
・実行とデバック→launch.jsonファイルを作成します→Java→設定完了

【困っていること】
・実行とデバックのプルダウンで、メインクラス（Launch Motocatalog Application）の選択肢がない

【確認したこと】
・実行とデバックのプルダウン確認→「Node.js」「構成の追加」が表示
・構成の追加→添付画像参照ください

【疑問点】
・該当の選択肢がないように見受けられます。どうしたら良いでしょうか。

<img width="1512" alt="0194D713-F44A-4EA3-B3DD-11D7C713AC83" src="https://user-images.githubusercontent.com/91002836/219923369-4758b258-23a5-4fd1-973b-d6b352deab24.png">

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
Javaのプロジェクトを開いていない状態で実行タブを開いてませんか？

**Comment by yoko-Developer** [comment]
無意識でしたが、キャプチャ見るとそんな感じですね。
今度から注意してみます。
