### ISSUE TITLE
クイックフィックスの表示

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#46]
動画と同じ挙動にならないため、質問させてください。
設定の問題でしょうか。
もしくは、どこかが間違えていますか？

【やったこと】
・beansにUserクラスを作成
・UserDetailsインターフェースを追加

【困っていること】
・Userのメソッド候補のクイックフィックスがクリックできない
・問題の表示をクリックすると、エラー詳細が表示される
<img width="1512" alt="F8FBA286-C27B-4BC9-AF0A-01506C640485" src="https://user-images.githubusercontent.com/91002836/220512233-123d0b6d-d08e-4e83-88b2-a748a72c910c.png">
<img width="1512" alt="B835085D-FAFF-4BA2-B161-711F57ED1B71" src="https://user-images.githubusercontent.com/91002836/220512249-1d1d9a53-1377-46f7-8726-b474575318f9.png">

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
クイックフィックスを確認していますと出ていますが時間が経っても出ませんでしたか？
↓このあたりもやってみましょうか。

- VSCodeを再起動してみる
- 他のコンパイルエラーが出ていないか確認
- 独自にインターフェース作ってクラスでimplementsしてみる

**Comment by yoko-Developer** [comment]
時間が経っても出てきませんでした。
>VSCodeを再起動してみる
改善しませんでした。

>他のコンパイルエラーが出ていないか確認
エラーはありませんでした。

>独自にインターフェース作ってクラスでimplementsしてみる
別ファイルでインターフェスを作って試すということでしょうか？

今回だけではなく、他のエラーとかファイルでも表示しないんです。
設定があるのかと思ったのですが、検索しても見当たらないんです。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
これはZOOMのとき一緒に見てみましょうか（笑）

**Comment by yoko-Developer** [comment]
@HyunwookPark 
わーい🙌
よろしくお願いします。
