### ISSUE TITLE
vuetifyインストール時のエラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#48]
vuetifyのインストールをしようと実行したところ、エラー表示されてしまいました。
関係ないかもしれませんが、sudoを付けても解決しません。

【やったこと】
・node.jsをインストールし、todolistプロジェクトを作成

【やってないこと】
・リポジトリ作成

【困っていること】
・vuetifyのインストールができない

【確認したこと】
・node.js：v16.16.0
・npm：v8.11.0
・yarn：v1.22.19
・Homebrew：v4.0.3

【エラーメッセージ】
・`vue add vuetify`
```
There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? （y/N)
```
→Yを選択（次に進まないため）
```
 ERROR  Error: command failed: npm install --loglevel error vue-cli-plugin-vuetify -D --legacy-peer-deps
Error: command failed: npm install --loglevel error vue-cli-plugin-vuetify -D --legacy-peer-deps
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/@vue/cli/lib/util/executeCommand.js:138:16)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```
<img width="1512" alt="71142E45-FE21-4917-987D-023F2A431225" src="https://user-images.githubusercontent.com/91002836/221406665-282fcd34-45ae-4d1a-8824-24324db200c1.png">

**Comment by yoko-Developer** [comment]
何度も最初から作り直し、とりあえずvuetifyのインストールはできました！

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
おーいえー！ナイス！！！
