### ISSUE TITLE
Gitリポジトリの作成

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#49]
【やりたいこと】
・ローカルで開発しているフォルダをGithubに保存したい
・ターミナル（コマンド）でリモートリポジトリを作成し、pushしたい

【やったこと】（時系列）
・git init→Reinitialized existing Git repository in /Users/yoko/vue/todolist/.git/
・mkdir gitinit
・cd gitinit
・mkdir gitinit
・cd [プロジェクトのあるディレクトリ]
・git add .
→
error: 'gitinit/' does not have a commit checked out
fatal: adding files failed
・rm -rf .git      gitを削除して
・git add .  
→fatal: not a git repository (or any of the parent directories): .git

【調べたこと】
・gitが2つある？
・リポジトリがあるディレクトリで実行しなければならない？

【試したこと】（時系列）
・Githubでリポジトリ作成
・git init
・git add .
→fatal: not a git repository (or any of the parent directories): .git

・git show
→fatal: your current branch 'main' does not have any commits yet

・cat .git/HEAD
→ref: refs/heads/main

・cat/refs/heads/main
→zsh: no such file or directory: cat/refs/heads/main

・git log
→fatal: your current branch 'main' does not have any commits yet

どうしたら良いでしょうか。
rm -rf gitinit　でディレクトリ削除すれば良いかなとも思いましたが、中のファイルも削除されると困るかなと思っています。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

`mkdir gitinit`が二回実行されているのが気になりますね。
ちなみにフォルダ名がコマンド名みたいで違和感あります（笑）

GitHubで初期にファイルが作成されないようにオプション選択せず
リポジトリを作ると手順が出てくるので参考にするといいかもです。

![image](https://user-images.githubusercontent.com/22320079/222653977-5d0a04fc-7708-49b0-abc6-6f92bf0e237b.png)
![image](https://user-images.githubusercontent.com/22320079/222654002-04ea7506-9638-4563-855c-5b2abacb5af0.png)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
時系列ですが、
どのディレクトリでなにをしているのかが省略されているのでわかりづらいですね。

**Comment by yoko-Developer** [comment]
motocatalogでプロジェクト作成の時にやっていた方法ですよね。
最初リモートリポジトリを作成していなかったので、`rm -rf .git`を実行した後に、何も選択しない方法でリモートリポジトリを作成しました。

エラーが出ているので手順が間違えているのは分かっているのですが、どこで間違えたのかがわからず・・。
git initができないことがそもそもの問題でしょうか。
ディレクトリを合わせて、時系列でやったこと全てを記載します。
よろしくお願いします。

・todolist　`$git init `
→fatal: not a git repository (or any of the parent directories): .git
・todolist　`$ git config --global user.name "xxxx"`
・todolist　`$ git config --global user.email "xxxxxx@gmail.com"`
・todolist　`$ mkdir gitinit`
・todolist　`$ cd gitinit`
・git init　`ls -a`
・gitinit　`$ git init`
→Initialized empty Git repository in /Users/yoko/vue/todolist/gitinit/.git/
・todolist　`$ git add .`
→error: 'gitinit/' does not have a commit checked out
・todolist　`rm -rf .git`
→fatal: not a git repository (or any of the parent directories): .git
・todo `$ git branch`
→main
・todolist　`$ git add .`
→fatal: your current branch 'main' does not have any commits yet
・todolist　`$ cat .git/HEAD`
→ref: refs/heads/main
・todolist　`$ git log`
→fatal: your current branch 'main' does not have any commits yet

**Comment by yoko-Developer** [comment]
改善理由は不明ですが、うまく行きました。
ありがとうございました。
