### ISSUE TITLE
GIthubについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#5]
pullとpushについて質問させてください。
pullは同じブランチ名の、リモートAブランチからローカルAブランチに反映させることしかできないと思っていました。
pushも同様に、ローカルにAブランチからリモートのAブランチのみにpushするもので、別のブランチに統合させるにはmergeを使うという認識です。
今までコマンドでしか操作したことがなかったのですが、業務でSourceTreeを使用しています。
SourceTreeには、別名のブランチからpullしたり別名のブランチにpushすることができそうです。
調べてみるとほとんど記事が見つかりませんが、時々conflictを起こす可能性があると記載がありました。
違う名前のブランチにpullやpushできるものでしょうか？

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
いい質問ですね！！さすがGit大好きyokoさん。

別名のブランチからpullしたり別名ブランチにpushしたりはできます。
これはSourceTreeを使っていなくても実行できます。

ただ、業務でよく使うかというとあまりそのような運用をするプロジェクトには出くわしたことがないです。
特別な理由がなければ同じ名前のローカルブランチとリモートブランチを関連付けるのがトラブルが少ないと思います。

**Comment by yoko-Developer** [comment]
@HyunwookPark 
ありがとうございます！！
Git大好きです😂大嫌いになることも多々ありますが・・・笑。

あーー、やっぱりできるんですね。
基本、使わない方がconflictも起こさず良い感じのようですね。
今のプロジェクトもそういう運用ではないのですが、SourceTreeを見てるとできそうだと思って疑問に思いました。
やはりmergeが王道ってことですよね。

もし、認識が間違えているようなら指摘していただけると嬉しいです😃
とりあえずこのIssueはクローズします。
ありがとうございました。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
その認識で合ってる思いますよー^^

**Comment by yoko-Developer** [comment]
ありがとうございます！
イケてるGitエンジニア目指します！！笑
