### ISSUE TITLE
Nuxt.jsでの表示

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#50]
初めてNuxt.jsの学習をしています。
思った通りの表示にならないので、見ていただけますか。

【やりたいこと】
・store>index.jsに記述した’Hello Vuex!'を表示したい
【やったこと】
・`npm run dev`で実行
・state>index.jsファイルに下記記述
```
import Vuex from 'vuex'

const createStore = () => { // アロー関数を使ってcreateStoreを定義
    return new Vuex.Store({
        state: function() {
            return  {
                message: 'Hello Vuex!'
            }
        }
    })
}

export default createStore
```
・pages>index.vueファイルに下記記述
```
<template>
  <section class="container">
    <div>
      <p>{{ $store.state.message }}</p>
    </div>
  </section>
</template>

<script>

export default {
}
</script>
```

【期待する出力】
・Hello Vuex!

【困っていること】
・ブラウザにHello Worldと表示される

【確認したこと】
・エラーなし

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
Node.jsの勉強というよりVueの勉強ですか？

`Hello World`という記述が残っている場所はありますか？
上記に貼ってくれたソースがすべてですか？

再起動は試しましたか？

**Comment by yoko-Developer** [comment]
すみません。
正：nuxt.js
誤：node.js
間違えました🙇
Hello Worldという記述はないです。
ブラウザはキャッシュクリア＆再起動しましたが、vscodeも再起動してみます。

**Comment by yoko-Developer** [comment]
状況が変わったので、時系列で記載させてください。
どこが間違えているのか分からないので、お願いいたします。

【やったこと】
・vscode再起動

【やっていないこと】
・state>index.jsファイル、pages>index.vueファイル以外への記述

【試したこと】
・npm run dev
→sh: nuxt: command not found
・npm install
・npm run dev
→ブラウザに何も表示しない
・npm update　(Browserslist: caniuse-lite is outdated. Please run next command npm update と表示があったため）
・npm run dev

【困っていること】
・ブラウザが真っ白で表示される

【GitHub】
https://github.com/yoko-newDeveloper/Node.js

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
んー、これだけの内容では何とも答えられないですねー。
nuxtは私も経験がないのでなんともですし環境を作るのも時間かかりそうですね。

**Comment by yoko-Developer** [comment]
ですよね。すみません。
修行して出直し、また質問するのでよろしくお願いします。
