### ISSUE TITLE
vscodeのターミナル

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#51]
ターミナルの起動時、zsh/bashが点滅します。
停止（⌃ c）でzshの表示で止まります。
停止まで点滅しているのは、正常な挙動でしょうか。
調べても見つけられないので、教えていただけますか。
よろしくお願いいたします。

![shell](https://user-images.githubusercontent.com/91002836/224529207-2f948603-457d-42bf-b12d-6ed9dea7d548.gif)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper うーん、どうなんでしょう。私の環境でも起きたことないですねー。Mac環境でのみ発生するのかな？
