### ISSUE TITLE
git pushできない

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#54]
【やりたいこと】
・ローカルからGitHubを作成し、pushしたい

【やったこと】
（時系列）
・ローカルでJavaプロジェクト作成
・GitHubでリポジトリ作成
・カレントディレクトリをJavaプロジェクトを作成したディレクトリへ移動
・GItHubに記載されている手順のコマンドを実行
```
git init
git add README.md
git commit -m "first commit"

// 強制的にmainブランチに変えるよ→既にmainブランチにいるため省略
// git branch -M main　

git remote add origin git@github.com:[アカウント]/[プロジェクト名].git
git push -u origin main
```
【困っていること】
・git add README.md実行
→fatal: pathspec 'README.md' did not match any filesが表示し、pushできない。

【調べて実行したこと】
・強制push`git push -f origin main`
→変わらず

【自力での解決】
(時系列)
・`git add .`→'git commit'→'git push -u origin mai'
・cat README.md
→'cat: README.md: No such file or directory'

【質問】
git add README.mdは、やっぱりいません。
リポジトリを確認すると、いつもREADMEが記載されている場所に「READMEをaddしますか？」（←英語）と記載されています。
addしたらREADMEが追加されましたが、どこで間違えたのでしょうか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
記載の手順のコマンドの前にREADME.mdファイル生成の手順が必要ですね。
githubをリモートで作成したときの手順にはREADME.md作成の手順が示されているはずです。
それを参考にするか自前でテキストエディタでもいいのでファイルを作成すると後続のgit addもきっとできますよ。

**Comment by yoko-Developer** [comment]
一番最初の行が
echo "# todolist" >> README.md
と記載されています。
実行してみましたが、`-bash: README.md: No such file or directory`と表示されてしまいます。
多分echo "# todolist" >> README.mdを実行したら良さそうですね。

**Comment by yoko-Developer** [comment]
何度かリポジトリとプロジェクトを作り直したら
`echo "# todolist" >> README.md`
todolistと記載されたREAD.MEが作成できました！
ありがとうございました。
