### ISSUE TITLE
GitHubのプログラム言語設定

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#55]
Javaで書いたコードでリポジトリを作成しました。
使用しているプログラミング言語は自動設定されると認識していますが、Kotlinが表示されています。
今後このリポジトリにマージするファイルも、全てJavaです。
変更方法が分からず困っています。
どうしたら変更できるでしょうか。

【試したこと】
・Settings」→「Pages」→Source」セクションを「main branch」に変更→「Save」

<img width="467" alt="スクリーンショット 2023-05-28 18 00 23" src="https://github.com/HyunwookPark/question-box/assets/91002836/efbda37b-4233-4053-9b05-8d825fd4bda5">

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
その部分は私も自動判別の認識ですね。
ちなみに私のリポジトリではそんなことなかったですけどねー。
放置するか、ktファイルが混ざってないか見直すかでしょうか。

**Comment by yoko-Developer** [comment]
やはり自動判別なのですね。
ktファイルがいました。
IntelliJでプロジェクトを作成する時に、Gradle DSLでKotolinがデフォルト選択されていたことが原因のようです。
Groovyに変更したら、いつもとおりJava100%で表示されました。
この２択について調べていますが、分かりやすいサイトが見つかっていません💦

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

解消されたようですね。

> この２択について調べていますが、分かりやすいサイトが見つかっていません💦

これはどういう意味ですか？

**Comment by yoko-Developer** [comment]
Gradle DSLで「Kotolin」か「Groovy」の2択です。
主語なしですみません・・。

**Comment by HyunwookPark** [comment]
> Groovyに変更したら、いつもとおりJava100%で表示されました。

ナイス対応！！

**Comment by yoko-Developer** [comment]
合ってるか分からないけど、取り敢えずこのまま行きます！
ありがとうございました。
