### ISSUE TITLE
mergeを取り消したい

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#57]
GitHubで、間違えてmergeまでしてしまいました。
revertコマンドで元に戻し再度PRまで実行したのですが、作成済みのクラスがPRから消えてしまったようです。
【やりたいこと】
・merge前の状態に戻したい
・更なる変更は加えたくない

良い方法を教えていただけますか？
よろしくお願いいたします。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
`git merge --abort`はどうですか？

**Comment by yoko-Developer** [comment]
mergeを止めておこう！！ってやつのようですね。
ちょっとやってみます。
ありがとうございます。
