### ISSUE TITLE
SpringBootビルド時エラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#58]
eclipseでSpringBootを作成したくて、操作しています。
ビルドできず、困っています。
どうしたら解決できるか、ご教示いただけますか。

【やったこと】
・Spring スタータープロジェクトを作成しようと操作
(操作手順：ファイル→新規→Springスタータープロジェクト(Spring Initializr)→必要項目入力後 「次へ」→新規Springスターター・プロジェクト依存関係（Lombok、Spring Boot DevTools、Spring Web、Thimeleaf選択）→完了）
・エラー表示されたため、Dependencesのチェックを外す

【困っていること】
・「入門コンテンツのインポートに問題が発生しました」と表示されて、進まない

【確認したこと】
・Javaバージョン：java -version→openjdk version "18.0.1"
・eclipseのJavaバージョン：キャプチャご参照（すみません、確認方法がよく分かりません）

【調べたこと】
・Dependencesを0個でビルドできる
・Java11以外だとspring3.0が対応しないので、バージョンアップが必要

![2619FA67-C943-436C-99C1-BC32822F6AE8_1_201_a](https://github.com/HyunwookPark/question-box/assets/91002836/04f7aed5-d779-45ce-965e-82e7330ae835)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
キャプチャで見る限り、
`repetition` プロジェクトの内容がSpring用のプロジェクトになっていないようですね。

「入門コンテンツのインポートに問題が発生しました」が表示されたとき、
他のエラーはありませんでしたか？
ネットワークの問題なのかな？gradleが利用されるのでライブラリを取得するのでそこでエラーになったのでしょうかね。

ちょっとなんとも言えないですね。
再度プロジェクトを作成してみましょぅか。

**Comment by yoko-Developer** [comment]
プロジェクトは何度も作成し直しているのですが、もう一度作成してみました。
作成手順は「やったこと」に記載している通りです。
やはり同様のエラーが表示されます。
「入門コンテンツのインポートに問題が発生しました」のエラーキャプチャと
コンソールエラーのキャプチャを添付します。

![86F8EBCB-82A4-4196-8E1E-B4C8EA44C270_1_201_a](https://github.com/HyunwookPark/question-box/assets/91002836/dd3b98bc-a316-4b08-b4bf-aeb28ba4b960)

![EC3C139F-474A-429B-8BB5-CFB7D63267E7](https://github.com/HyunwookPark/question-box/assets/91002836/3dd74549-0379-4668-a78d-afd619192bfe)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
出てきたエラーについてインターネットで探してみましたか？

考えられること

- 指定のバージョンのSpringフレームワークが存在しない・アクセスできない
- 利用しているJavaバージョンとフレームワークの整合性が合わない

このあたりで見直してみてはいかがでしょうか？

**Comment by yoko-Developer** [comment]
結構検索したんですけど、JavaもSpringも最新のようで・・
解決できず困っている状況です。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
利用しているbuild.gradleファイルの内容を貼って頂けますか？

**Comment by yoko-Developer** [comment]
build.gradleはできていたので添付します！
```
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.1.0'
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

**Comment by HyunwookPark** [comment]
javaのバージョンは17のようですね。

**Comment by HyunwookPark** [comment]
![image](https://github.com/HyunwookPark/question-box/assets/22320079/2787f725-223f-48a1-a6db-3361badc5f86)
![image](https://github.com/HyunwookPark/question-box/assets/22320079/84c75b79-81c6-49d0-bf97-1962005f785b)
![image](https://github.com/HyunwookPark/question-box/assets/22320079/d8d4ecc5-3c06-46d5-93fa-8786c0daa4c7)

こちらで試してみたところ普通にプロジェクト作成できてしまいましたね。

**Comment by HyunwookPark** [comment]
他に考えられるのはworkspaceのどこかの設定ファイルの破損とかでしょうか。
workspaceを新たに作成するという方法も考えられますが、
色んな設定をしているということであればその設定はworkspaceで管理していることが多いので
再設定が必要になるかもしれません。

**Comment by yoko-Developer** [comment]
workspaceではなく、ローカルに作成していたのですが。。
念のためデフォルトのworkspaceに作成してみましたが、同様のエラー表示されてしまいました。
このMac購入した時からworkspaceには作成しなかったのですが、具体的に再設定とは例えばどういうものでしょう？
再インストールしたら、改善しそうでしょうか。

**Comment by HyunwookPark** [comment]
基本的にはeclipse起動するときworkspaceを作っているはずですね。
別のworkspaceに切り替える方法を試してからの方がいいかもしれません。
新しく再インストールしてもworkspaceが残っていればそのworkspaceを使うかもしれないからです。

**Comment by yoko-Developer** [comment]
すみません！
別のworkspaceに切り替えるというのは、違うローカルにプロジェクトを作成してみて試すということでしょうか？

**Comment by yoko-Developer** [comment]
恐らくM1対応してないようです・・。
