### ISSUE TITLE
A5:SQL Mk-2のテーブルについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#6]
いつも「VSCodeでSpringBoot開発」で学習させていただいています😃
初めてA5:SQL Mk-2を使用するということもあり、何かするたびにエラーが出ています。
テーブルにテストデータをINSERTすることができなくて、ベテランエンジニアの知り合いに助けを求めたところ、TablePlusで操作することを勧められて、言われた通りに実行してテストデータはINSERTできたはずです。
#07.データベースを準備の21:46辺りでカラムを確認すると思うのですが、A5:SQL Mk-2のカラムタブを開くと「論理名」がブランクになっています（画像1枚目）。
これは何故でしょうか。。。どこで間違えたのか分かりません。。。

21:53辺りの「データが入ったか更新してみましょう」を実行したら「2 Z900RS」しか表示されていません（画像2枚目）。
再度INSERTからやり直そうと思って実行したら「m_motorcycleテーブルが見つかりません」というようなエラーが表示しました（画像3枚目）。

状況が把握できないので、コマンドで確認しようとデータベースを表示しましたが、「motocatalogdb」がありません（画像4枚目）。
「127.0.0.1」というデータベースは作成していただいたこともあり、どういう表記になるのか分かりません。でもそれらしいデータベースも見当たりません。

MySQLで「motocatalogdb」やテーブルを作った方が早くて良いとも思いますが、極力先生と同じ方法で進めたいと思っています。
現在どういう状況になっているのかもよく分からず、混乱しています。
どうか助けてください🙇

最初からやり直そうと、データベース設定から実行しました。
初回と同様に、動画と同じ条件で作成ができません。
このエラー（画像5枚目）が表示したため、代替策で現在の状態になっていますが、この時点から作り直すにはどこが間違えているのでしょうか。
エラー表示されているパスワードは、vscodeからコピーしています。

![2EE616FB-DFDF-4EF0-AF2C-668F75857296_1_201_a](https://user-images.githubusercontent.com/91002836/194709727-48b6f64d-9c95-483d-b5de-3759c5831ba7.jpeg)
![508E95C3-ABD0-4DB2-8622-76A844E29868](https://user-images.githubusercontent.com/91002836/194709784-98d6d8d3-f254-45c2-97ba-f42eec1d83fc.jpeg)

![E83A902B-9D09-453A-8735-A274754
![F3B1088B-AD92-465E-9B72-0AB3EC5B1639_1_201_a](https://user-images.githubusercontent.com/91002836/194709792-95b71d48-ba2e-43e7-bb0b-c6a5ec606ca2.jpeg)
1D2D2](https://user-images.githubusercontent.com/91002836/194709789-6fdb85d6-3069-4431-9e80-fc5466085bf0.jpeg)
![F3B1088B-AD92-465E-9B72-0AB3EC5B1639_1_201_a](https://user-images.githubusercontent.com/91002836/194709911-68a12cbb-a5a3-4f1b-a1aa-4f75f84e8cf0.jpeg)
![414442C7-A0B6-403C-ACCC-D26F22C2EA8D_1_201_a](https://user-images.githubusercontent.com/91002836/194799456-f4f7a6a4-baa0-459a-931b-2162b69d85f6.jpeg)

**Comment by yoko-Developer** [comment]
分からなすぎてA5:SQL Mk-2の内容を、全て削除しました。
MySQLでデータベースとテーブル作成し、テストデータも入力できました🙌
そしてA5:SQL Mk-2に反映して、確認することもできました🙌
アプリ側で設定するとまたエラー表示するかもしれませんが、またその際は相談させてください。

**Comment by yoko-newDeveloper** [comment]
当然だと思いますが、下記エラーが表示します。

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


application.ymlにどう書いて良いのか分かりません。
MySQLで設定したので、散々苦労して設定したDockerは無関係だと思います。
こんな感じで大丈夫でしょうか。。。
spring:
 datasource:
  driverClassName : com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/データベース名
  username : XXXXX
  password : YYYYY

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
A5:SQL Mk-2の設定を削除して再度試したらうまく動いたということはなにか手順が前回とは違うようですね。

> 「論理名」がブランクになっています（画像1枚目）

この件も解消できましたか？
CREATE文の`COMMENT`の書き漏れかなと思いますが。

**Comment by yoko-Developer** [comment]
A5:SQL Mk-2が、ログイン情報で起動しなくなってしまいました。
「論理名」も解消できないまま、削除してしまいました。
A5:SQL Mk-2に記載したのは下記です。
間違えているでしょうか？
MySQLに記述したら、A5:SQL Mk-2でも論理名が表示されました。
--モーターサイクルマスタのテーブル作成
CREATE TABLE m_motorcycle(
	moto_no INT NOT NULL PRIMARY KEY COMMENT 'バイク番号',
	moto_name VARCHAR(100) COMMENT 'バイク名',
	seat_height INT COMMENT 'シート高',
	cylinder INT COMMENT 'シリンダー',
	cooling VARCHAR(20) COMMENT '冷却',
	price INT COMMENT '価格',
	comment VARCHAR(200) COMMENT 'コメント',
	brand_id VARCHAR(2) COMMENT 'ブランドID',
	version INT COMMENT 'バージョン',
	ins_dt DATETIME COMMENT '登録日時',
	upd_dt DATETIME COMMENT '更新日時'
) COMMENT 'モーターサイクルマスタ';

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
CREATE文はMySQLのコマンドから実行して論理名も出るようになったということですかね。
A5:SQL Mk-2の状態を見ていないのでわかりませんが、
もしかするとMacから動かしているのが影響しているのでしょうか。

SQLツールはA5:SQL Mk-2を無理に使うことはありません。
Macで使いやすいものや、MySQL付属のツールでもいいと思います。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
結局ZOOMでの対応になりましたね。^^;
やはり文章でのやりとりには限界がありますね。

でもすんなり解決できてよかったです。

**Comment by yoko-Developer** [comment]
昨日はありがとうございました。
文章力がないのが問題だと思っています😢
先生のおかげで、解決できました！！
MySQL付属のツールもあるんですね。。
色々調べて研究してみたいと思います。
業務では何使うか分からないので、色んなツールを使用できる方が良いと思います。
A5:SQL Mk-2はおかげで解決したようなので、クローズします。
ありがとうございました。

**Comment by HyunwookPark** [comment]
質問ありがとうございます！
いろんな質問を頂けて嬉しいです。^^

**Comment by yoko-Developer** [comment]
やはり神です！
疑問だらけなので質問攻めですが、末長くよろしくお願いいたします🥺
