### ISSUE TITLE
vue.jsのブラウザ表示について

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#60]
新規プロジェクトskiresort_information(アンダーバー)を作成しました。
element-uiは成功しました。

【やったこと】
- プロジェクト作成
- element-ui導入->下記コマンド実行にて、画像の通り真ん中にel-buttonがある状態を確認

[参照URL](https://tech.amefure.com/js-vue-element-ui)

```
 % cd element-app
 % yarn serve
```
[GitHub リポジトリ](https://github.com/yoko-newDeveloper/skiresort_information)

![E2210E55-6E2C-40B5-88DA-755DAA71F476_1_105_c](https://github.com/HyunwookPark/question-box/assets/91002836/cb5f113e-6b71-4356-9ed6-fe85f72b1b33)

- `% cd skiresort_information`　実行し、elementのtableを貼る
```
<template>
    <el-table
    :data="tableData"
    stripe
    style="width: 100%">
    <el-table-column
      prop="date"
      label="Date"
      width="180">
    </el-table-column>
    <el-table-column
      prop="name"
      label="Name"
      width="180">
    </el-table-column>
    <el-table-column
      prop="address"
      label="Address">
    </el-table-column>
  </el-table>
  <!-- <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div> -->
</template>

<script>
export default {
  data () {
    return {
      tableData: [{
        date: '2016-05-03',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }, {
        date: '2016-05-02',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }, {
        date: '2016-05-04',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }, {
        date: '2016-05-01',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }]
    }
  }
}
// // @ is an alias to /src
// import HelloWorld from '@/components/HelloWorld.vue'

// export default {
//   name: 'HomeView',
//   components: {
//     HelloWorld
//   }
// }
</script>

```

【困っていること】
-skiresort_informartionをカレントにして`yarn serve`実行するとテーブルが表示されず真っ白になってしまう。

![0E47CB7F-CE71-44A9-ABF0-FA6DCABAA75B_1_105_c](https://github.com/HyunwookPark/question-box/assets/91002836/1716942a-729d-46be-b556-0c3df2c83293)

- 開発者ツールでエラー表示がある

![0694FA3D-E8AF-43E4-8CCE-7DD6AC0D94E9](https://github.com/HyunwookPark/question-box/assets/91002836/179aa96f-d0aa-46f7-8fcb-fcc74dd2e4a4)

【質問】
この実装でストライプのテーブルが表示されることを昨日も確認しましたが、<nav>のタブ以外何も表示されません。
開発者ツールでエラーが出るのは何かしら問題があるとは思いますが、どうしたら良いのか分かりません。
テーブル表示させるためには、どうしたら良いでしょうか。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
合宿のときに作ったプロジェクトと比較しながら違いを検討してみましょう。
App.vueの内容が異なるはずです。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

App.vue

```html
<template>
  <el-main>
    <router-view/>
  </el-main>
</template>

<script>

export default {
  name: 'app',
  components: {
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

このようにどのvueを表示するのかを<router-view/>を使って実装できているか確認してください。

**Comment by yoko-Developer** [comment]
App.vueを教えていただいたコードに修正しましたが、やはり表示が変わりません。
ちなみにformも変わりません。
もう少し修正が必要ですか？

私の記憶では`/' はHomView、　'/About' は/aboutで表示されると教えていただきました。
それが書いてあるのがApp.vue なのか、main.jsなのか分からなくなってしまいました。
そこに関係あるのか分かりませんが・・・。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
連携してもらったリポジトリは最新コードではないようですね。

element-uiを入れた後に編集したのは以下の部分だけです。

HomeView.vue（yokoさんが貼った内容のまま）

```html
<template>
    <el-table
    :data="tableData"
    stripe
    style="width: 100%">
    <el-table-column
      prop="date"
      label="Date"
      width="180">
    </el-table-column>
    <el-table-column
      prop="name"
      label="Name"
      width="180">
    </el-table-column>
    <el-table-column
      prop="address"
      label="Address">
    </el-table-column>
  </el-table>
  <!-- <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div> -->
</template>

<script>
export default {
  data () {
    return {
      tableData: [{
        date: '2016-05-03',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }, {
        date: '2016-05-02',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }, {
        date: '2016-05-04',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }, {
        date: '2016-05-01',
        name: 'Tom',
        address: 'No. 189, Grove St, Los Angeles'
      }]
    }
  }
}
// // @ is an alias to /src
// import HelloWorld from '@/components/HelloWorld.vue'

// export default {
//   name: 'HomeView',
//   components: {
//     HelloWorld
//   }
// }
</script>

```

App.vue

```html
<template>
  <el-main>
    <router-view/>
  </el-main>
</template>

<script>

export default {
  name: 'app',
  components: {
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

連携してもらったリポジトリの内容を再度見てみたところ、
vueプロジェクトがネスト形式に2重になっています。
プロジェクトを再作成してください。

![image](https://github.com/HyunwookPark/question-box/assets/22320079/ad132c1c-b0a8-4124-a87e-b73ce0d3db2e)

**Comment by yoko-Developer** [comment]
色々失敗してたことに気づき、数回作り直しました。
先ほどは最新をpushしていなくてすみません。

今度はネストしてないし大丈夫だと思っていますが（毎回）、全く画面に表示されなくなってしまいました。
何度も申し訳ありませんが、確認していただけますか。

[GitHubリポジトリ](https://github.com/yoko-newDeveloper/skiresort_information)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

エラー内容を読んでいないように思います。
開発者ツールのエラーを嫌がらずにちゃんと読みましょう。

![image](https://github.com/HyunwookPark/question-box/assets/22320079/0e7829ff-4143-4eb3-a6ab-3a054fb0d8b6)

内容を見たところ、そもそも`<el-table>`というカスタムタグが使えないよというエラーに思います。

```console
vue add element
```

が反映されていません。

正しくelement-uiがインストールされている場合、

package.jsonに`"element-ui": "^2.4.5"`が含まれます。

```json
  "dependencies": {
    "core-js": "^3.8.3",
    "element-ui": "^2.4.5",
    "vue": "^2.6.14",
    "vue-router": "^3.5.1"
  },
```

**Comment by yoko-Developer** [comment]
すみません、開発者ツールは未確認でした・・。
このエラーは昨日から何をやっても表示されてしまいます。
真ん中にel-buttonの表示は出たんですけど、もう一度element-uiの導入を試してみます。

**Comment by yoko-Developer** [comment]
やってみましたが、どうしてもdependenciesに"element-ui": "^2.4.5",が追加されません。
ビルドしたときにel-buttonは表示されるのですが、何度やっても追加されてくれません。

**Comment by yoko-Developer** [comment]
elementの導入部分の動画を収録しました。
雑な編集ですが、ご確認いただけますか。
よろしくお願いします！
![element導入1](https://github.com/HyunwookPark/question-box/assets/91002836/03d0944b-3002-4c6a-8c96-21d05c72f4b6)
![element導入2](https://github.com/HyunwookPark/question-box/assets/91002836/ed12d35a-069d-4292-b559-fea668c43a86)
![element導入3](https://github.com/HyunwookPark/question-box/assets/91002836/9f169b96-1ee6-410f-b90b-06c7ac88bbb9)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
見た感じではまだプロジェクトはネストしています。
`src`フォルダが`skiresort_information`直下と`element-app`直下に存在します。
プロジェクトを再作成したのであれば、プロジェクトの作り方が正しくないように思います。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
ちなみに、その動画の撮り方は文字が小さくて雰囲気で判断する必要があります。
もっと解像度高い動画の撮り方が嬉しいなあ。

**Comment by yoko-Developer** [comment]
ファイル開いていると、一番上にOPEN DITORSが表示されるので、ファイルは一旦クローズしました。
ネストしていますか？

動画は、全画面止めて拡大収録に挑戦します。
もしくはiPhone撮影で！！
![02A8E234-CE1B-452A-BEE7-AE6A97236FB4](https://github.com/HyunwookPark/question-box/assets/91002836/95f512cd-622f-4176-8690-756642cd56f1)

**Comment by yoko-Developer** [comment]
ありがとうございました！！
おかげで環境構築はできそうです。
