### ISSUE TITLE
パスでの切り替え

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#61]
HomeView.vueとApp.vueの雛形のみですが実装しました。
ビルドすると、ブラウザにlocalhost:8080と入力しても`/about`画面しか表示されません。
router/index.htmlは変更等していません。

HomeView.vue画面が表示しなくなってしまった原因がわからず困っています。
よろしくお願いします。

[GitHubリポジトリ](https://github.com/yoko-newDeveloper/skiresort_information)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

App.vueに入力画面の項目を実装したからですね。

App.vueはアプリケーション全体の枠組みです。
ヘッダーやフッターやサイドメニューなどアプリケーション全体に影響するもの以外は実装することはありません。

また、変更前に書いてあった `<router-view/>` はVue Routerで特定の画面を表示するための機構です。
今回の場合、これを削除すべきではないと思われます。

何度かお伝えした内容なのでしっかり整理しましょう。
また、Gitの履歴で変更点を差分として確認できるので自分がなにを変更して動きが変わったのかを把握できるようにしましょう。

**Comment by yoko-Developer** [comment]
完全に勘違いしていました。
AboutViewを変更したと思い込んでいました。
修正しておきます。
ありがとうございました。
