### ISSUE TITLE
テストコードのパターンについて

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#64]
Java APIの相関チェックのバリデーションを実装しています。
【アプリケーション概要】
人気のスキー場の名称、エリア、顧客評価に関するCRUD処理と自動テストを行えるアプリケーション

【現在の仕様】
- 項目名：name,area,customerEvaluation
- 登録時：全ての項目にサイズ(`@Size`)、null,空文字,半角スペースを許可しない(`@NotBlank`)バリデーション及びテストを実装
- 更新時：登録時と同様

【やりたいこと】
-  更新時はどれかひとつのみ入力すればバリデーションエラーとならないように修正したい

【迷っていること】
- テストパターンをどこまでやるべきか

【相談内容】
境界値のテストができないプロジェクトの場合、どのテストパターンを実装すれば良いのかを迷っています。
ぱっくんちょ先生がレビュアの場合にどのテストを実装していればOKですか？
よろしくお願いいたします。

## NGパターン

|       value        |  NG  | NG | NG  | 
|:------------------:|:----:|:--:|:---:|
|        name        | null | "" | " " | 
|        area        | null | "" | " " |
| customerEvaluation | null | "" | " " | 

##  nameOKパターン

|       value        |  OK   |   OK   |  OK   |  OK   |   OK   |  OK   |  OK   |   OK   |  OK   |  OK   |  OK   |  OK   |  OK   |  OK   |  OK   |
|:------------------:|:-----:|:------:|:-----:|:-----:|:------:|:-----:|:-----:|:------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
|        name        | goryu | goryu  | goryu | goryu | goryu  | goryu | goryu | goryu  | goryu | goryu | goryu | goryu | goryu | goryu | goryu |
|        area        | null  | nagano | null  |  ""   | nagano |  ""   |  " "  | nagano |  " "  | null  |  ""   | null  |  " "  |  ""   |  " "  |
| customerEvaluation | null  |  null  | good  |  ""   |   ""   | good  |  " "  |  " "   | good  |  ""   | null  |  " "  | null  |  " "  |  ""   |

##  areaOKパターン

|       value        |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   |   OK   | OK | OK |
|:------------------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:--:|:--:|
|        name        |  null  |  null  |   ""   |   ""   |  " "   |  " "   |  null  |   ""   |  null  |  " "   |   ""   |  " "   |        |    |    |
|        area        | nagano | nagano | nagano | nagano | nagano | nagano | nagano | nagano | nagano | nagano | nagano | nagano | nagano |
| customerEvaluation |  null  |  good  |   ""   |  good  |  " "   |  good  |   ""   |  null  |  " "   |  null  |  " "   |   ""   |

## customerEvaluationOKパターン

|       value        |  OK  |  OK  |  OK  |  OK  |  OK  |  OK  |  OK  |  OK  |  OK  |
|:------------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
|        name        | null |  ""  | " "  | null |  ""  | " "  | null |  ""  | " "  |
|        area        | null |  ""  | " "  |  ""  | null | null | " "  | " "  |  ""  |
| customerEvaluation | good | good | good | good | good | good | good | good | good |

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
なるほど。
私ならnullと""は同じ扱いとしてテストを実施すると思います。
ただし、validationを行う前に""をnullに変換するという仕組みする前提です。

こんな感じです。

| # | name  | area   | customerEvaluation | Expected Result |
|---|-------|--------|--------------------|-----------------|
| 1 | goryu | nagano | good               | OK              |
| 2 | goryu | nagano | null               | OK              |
| 3 | goryu | null   | good               | OK              |
| 4 | goryu | null   | null               | OK              |
| 5 | null  | nagano | good               | OK              |
| 6 | null  | nagano | null               | OK              |
| 7 | null  | null   | good               | OK              |
| 8 | null  | null   | null               | NG              |

**Comment by yoko-Developer** [comment]
ありがとうございます。
8パターンですね！
""をnullに変換するというのは、どういうことでしょうか？
そういうロジックを書くのですか？

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
Youtubeの講座でもやっているように
テキストフィールドから入力された内容で""をnullに置換する方法です。
この方法を採用する場合、部品を作るのが一般的ですね。

**Comment by yoko-Developer** [comment]
ありがとうございます。
もう一度しっかりYouTubeを見て、挑戦したいと思います。
早く余裕でできる日が来て欲しいです...。
