### ISSUE TITLE
expected: のエラー

### ISSUE THREAD

**Issue by yoko-Developer** [HyunwookPark/question-box#7]
またまた質問お願いします。
「VSCodeでSpringBoot開発 #08.データベースアクセス」を実施しています。
36:52辺りでエラー表示されていて、解決策が分かりません。
（画像1枚目）
expected cannot be resolved to a variableJava(33554515)
→expected は変数に解決できません

Syntax error on token \":\", invalid AssignmentOperator Java(1610612971) 
→文法上のエラーだと思いますが「:」は記述されていて、削除してもエラーが消えません。
![7B47BE26-084D-42F3-A5DE-1F7594C71A72_1_201_a](https://user-images.githubusercontent.com/91002836/196042304-824f6fd1-5efd-4bb9-98f5-bbdfb7dffcd0.jpeg)

クイックフィックスを実行すると変数宣言されて「expected 」のエラーは解消されますが、動画と違ってしまうので、違うところに原因があると思っています。
また、「:」のエラーについてはフィックスがありません。
（画像2枚目）
![2BF01E17-5BBE-4476-83C9-30CF562B553A_1_201_a](https://user-images.githubusercontent.com/91002836/196042314-ef0791e3-f9d6-42fe-b632-92ed53038a70.jpeg)

どうすれば宜しいでしょうか。

現在カラー設定を変更したのですが、1枚目画像にはグレーアウトして表示されている箇所があります。
このグレーアウトは、変数宣言されていないということだと聞きました。
vscodeには、判断できる仕様があるのでしょうか？
検索しても、そのような仕様があるという情報が得られませんでした。

よろしくお願いいたします。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

`expected:`の部分はVSCodeが仮引数の名前を見せてくれているだけなので、
コードとして書く必要はありません。

VSCodeの親切心なんだけど、知らない人にはちょっとわかりづらいかもしれませんね。

**Comment by yoko-Developer** [comment]
Javaでテストコードを書いたのが初めてで、そんな仕様があるとは知りませんでした。
vscodeは初めて使用していますが、ecripseでも同様の仕様があるのでしょうか？
ecripseでは引数が勝手に入って、エラーが出たことがありません。
知識がないから出るエラーなのですが。。。

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
Eclipseではこの機能は基本ないので
この点のコーディング間違いはないと思います。

**Comment by yoko-Developer** [comment]
やっぱりEclipseにはない機能なのですね。
勉強になります！
#09に進んでいますが、早速エラー表示されて解決できません。
SQLを書き換えてテスト実行したら、2枚目のキャプチャが表示しました。
印が付いているところには間違いがないと思っているのですが、どの辺に問題があるのか教えていただけますか。

![BC08E927-3A6D-4AC7-9090-D81E3DE4AD69](https://user-images.githubusercontent.com/91002836/198023344-a0509823-d10f-41a9-aa2b-1291aa4842b4.jpeg)
![9AC3EED6-08BD-4BC4-B51E-026C09B39D43](https://user-images.githubusercontent.com/91002836/198042636-0381b72b-270c-4767-a39a-bcecd0f70fc2.jpeg)

**Comment by yoko-Developer** [comment]
import文を手入力する必要がありましたね・・。
`import static org.assertj.core.api.Assertions.assertThat;`
「⌘ ＋ Shift ＋ O」を実行したら、自動的に削除されてしまいます。
自動的に削除されたということは、不要なのでしょうか。

ひとまずimport文は入力したままにしてみたら、違うところがエラーになってしまいました。
エラーメッセージ
`The method isEqualTo(String) is undefined for the type Object`
「メソッドisEqualTo(String)はObject型では未定義である。」
同様にimport文なのかなと思いましたが、検索しても該当であろう記事が見つけられません。
どうしたものでしょうか・・・。

![B7D3883F-21AE-4C36-A0B8-56DF9018617F](https://user-images.githubusercontent.com/91002836/198821054-e15c5802-6442-4953-be43-49b5eb0aa0d9.jpeg)
![6CA41269-9919-4FFF-AB1F-15B70CAF0A37](https://user-images.githubusercontent.com/91002836/198821059-a24af0f6-4fc5-4921-8ab5-d2e12b6674d8.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 
そうですね。import文が必要ですね。
`import static org.assertj.core.api.Assertions.assertThat;`
はコード内で使われていれば自動importの機能で削除されることはないんですけどねー。

また、`The method isEqualTo(String) is undefined for the type Object`も謎ですね。。
メソッドが定義されていないということなのでimport文が原因ではなさそうです。

いまのキャプチャーを見る限りでは問題なさそうなんですが。。

isEqualToメソッドは`assertThat(moto.getBrand().getBrandName())`でドットを入力したときに候補として出ましたか？

**Comment by yoko-Developer** [comment]
やはりimport文は必要ですよね。
`assertThat`のエラーはなくなったんですけど・・。
もう一度「⌘ ＋ Shift ＋ O」を実行してみましたが、やはり自動的にimport文が削除されてしまいます。

候補が出るか、検証してみました。
「isEqualTo」メソッドは候補の中に出ていないようです。
アプリの実行や、その前のMapperクラスのリストのテストは成功したのですが・・・。
![8FB53897-C69D-4C21-855E-9428F573CED6_1_201_a](https://user-images.githubusercontent.com/91002836/198838124-9e17427c-5612-4a5a-93f0-93cb56f3fee3.jpeg)

**Comment by HyunwookPark** [comment]
@yoko-newDeveloper 

あ、見つけた！！
↓この部分が怪しいです。

![198838124-9e17427c-5612-4a5a-93f0-93cb56f3fee3](https://user-images.githubusercontent.com/22320079/199403162-d7864f31-eb8d-47b5-b40c-710507c32fdb.jpg)

自動import文の機能でimportが消えるということは、そのimportを使っていないということですね。
赤で囲った部分で独自にメソッドを用意しているのでそれが邪魔をしていますね。

そのあたりを調査してみてください。

**Comment by yoko-Developer** [comment]
47、48行目を削除したら動きました！！
ありがとうございます。
どこからあのメソッドが現れたのか、全く謎です・・・。
多分削除しわすれたんでしょうね。
いつもエラー解決すると嬉しいですが、同時に悲しくなります。
とりあえず、これで進むことができます！！

**Comment by HyunwookPark** [comment]
ヒャッハー！！

**Comment by yoko-Developer** [comment]
ありがとうございました！
