### ISSUE TITLE
エンジニア経験者の技術経歴書にはどんな内容が好ましいのでしょうか？

### ISSUE THREAD

**Issue by otowmoyarng** [HyunwookPark/question-box#8]
日本語で投稿させていただきます。
エンジニア経験者の技術経歴書の記載内容について質問があります。

エンジニア経験者の技術経歴書は現場の実績が時系列に書かれたエクセルまたはPDFが多い印象です
この様式だと営業にはいいのかもしれませんが、エンジニアが技術力を判定するのは難しいと思います。
かといって実績を細かく記載されても、それはそれで読むのがしんどい

先生は、技術経歴書にどんな内容が記載されていていればいいとお考えでしょうか。
そもそも経験者にポートフォリオや技術経歴書や不要とお考えでしたら、その理由もお聞かせください。

ちなみにこのような質問はTwitterやYoutube等で既に説明済でしたら調査不足ですみません。
そのURLを共有していただけませんか。

以上です。よろしくお願いします。

**Comment by HyunwookPark** [comment]
@otowmoyarng 

> 日本語で投稿させていただきます。

むしろ日本語でお願いします（笑）

> 先生は、技術経歴書にどんな内容が記載されていていればいいとお考えでしょうか。

難しい質問ですね。
技術経歴書の用途としては案件・プロジェクト・入社などで技術力等を判断するものですし、
以下の点が書かれていればいいかなと思います。

- 時系列の現場の実績
    - メイン技術をどれほどの期間使ったのか判断
    - 経験した業務の種類を確認
- 経験のある技術の羅列
    - 可能なら得意順
    - 利用期間もあると嬉しいけど、情報量多いから得意順だけでもよさそう
- アピールポイント
    - 個人的にはかなり重要な認識
    - 得意分野、プロジェクトの中での役割、取り組む姿勢、普段の考えなど

最近であれば以下のもあるとよさそうです。

- SNSアカウント
- 執筆のブログ
- GitHubアカウント

**Comment by HyunwookPark** [comment]
@otowmoyarng 
実績が少なめならポートフォリオも欲しいところですね。
ポートフォリオは継続的にメンテナンスするなら有効かもしれませんが、
あまりしょぼいものなら現役エンジニアとして営業活動する時点ではむしろ邪魔かと思います。

技術経歴書は営業でも使いますが、
自分の経験した技術を整理しておくうえでいい資料だと思います。
多くの会社では営業担当が作成している認識ですが
ぜひ技術者個人個人が意識して作ってほしいです。

**Comment by HyunwookPark** [comment]
このような議論はとても建設的でいいですね！さすがです。
ぜひとも色んな場で多くの人の意見を聞きたいものです。

@otowmoyarng さんの技術経歴書への考えもぜひお聞かせください。

**Comment by otowmoyarng** [comment]
技術者が自分の経験をふりかえって経歴書に落とし込んでいく、これはいいですね。
私も定期的にふりかえって経歴書に棚卸ししてみます。

経歴書に文字だけはわかりにくいので、図や表も含めてアピールしてもいいかと思ってます
経験多いなら星取表を用いて使用言語やフレームワーク、担当できる工程を記載するとスキルが見やすいし、
逆に経験少ない人ならレーダーチャートを用いてアピールポイントを見やすくしてもいいかもしれません

改めて考えてみたら経歴書は見る人（営業担当者・エンジニア）によって目的が違いますね。
これって設計書をどこまで書いたらいいか、永遠のテーマに近いものを感じました。

難しい質問でしたが対応していただき、ありがとうございました。
丁寧な回答をいただき、勉強になりました。

**Comment by HyunwookPark** [comment]
@otowmoyarng 
なるほど、図や表ですか。確かに視覚的に効果的ですね。
参考になります！
星取表は確かに使っている会社さんもありますね。
フォーマット作成にかなり時間をかけている会社さんでした。
技術がどんどん進歩するので毎回フォーマットを見直す手間はありますが、
見る側にとっては嬉しいですね。

レーダーチャートは新しいですね。
性格上のレーダーチャートやMBTI（性格診断）の内容を記載するのも面白そうです。

**Comment by HyunwookPark** [comment]
@otowmoyarng 
議論が終わったようなのでクローズしますね。
